import type { SimulationCaseInput } from "@/domain/case";
import { caseFact } from "@/domain/provenance";
import {
  DOCS_ASSUMPTION, FICTION_ASSUMPTION, INVESTIGATION_PROMPT, RHUS_PLAN, amount, choice, concept, cpt, eobLine, fact, icd,
  investigation, knowledge, memberReply, planRulesDoc, rule, selectAll,
} from "./helpers";

// =============================================================================
// CASE 01 · Foundation · Reading a paid EOB
// =============================================================================
export const case01: SimulationCaseInput = {
  id: "case-01-first-eob",
  version: 1,
  portfolioNumber: 1,
  code: "CASE-01",
  title: "\"Do I owe $285?\": reading a paid EOB",
  summary: "A member receives their first EOB for an in-network sick visit and reads 'Amount billed: $285' as a bill.",
  scenario: "In-network PCP visit paid in full. Member mistakes the EOB for a bill and the billed amount for what they owe.",
  recordingPriority: "high",
  difficulty: "foundation",
  status: "ready",
  isSample: false,
  caseTypes: ["eob_investigation", "coding"],
  skills: ["eob_reading", "allowed_amount", "member_responsibility", "cpt", "icd10", "plain_english"],
  knowledge: knowledge(
    ["rhus.benefit.pcp_visit", "rhus.cost.in_network_no_cost_share", "rhus.cost.deductible.in_network", "rhus.structure.in_network_direct_billing"],
    ["eob", "billed-amount", "allowed-amount", "contracted-rate", "plan-payment", "member-responsibility", "provider-statement", "cpt", "icd10", "member-communication", "care-coordination"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-08-02T16:40:00Z",
    memberMessage:
      "Hi! I got a letter from my health plan about my doctor visit in July. It says \"Amount billed: $285.00\" in big letters. Do I need to pay this? I don't see a due date anywhere. And what does \"allowed\" mean? Sorry, this is my first time using US insurance.",
  },
  member: { name: "Priya Natarajan", memberId: "RHU-20417-01", details: "Employee, enrolled 2026" },
  plan: RHUS_PLAN,
  provider: { name: "Maple Street Family Medicine", type: "Primary care practice (fictional)", networkStatus: "in_network" },
  codes: [cpt("99213", "Office visit, established patient, low-to-moderate complexity."), icd("J02.9", "Acute pharyngitis (sore throat), unspecified.")],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION, "No provider statement has arrived yet."],
  documents: [
    {
      id: "doc-claim",
      type: "claim",
      title: "Claim record",
      provenance: caseFact(),
      claimNumber: "CLM-26-0711-1182",
      status: "processed_paid",
      receivedDate: "2026-07-10",
      processedDate: "2026-07-24",
      billingProvider: "Maple Street Family Medicine",
      networkStatus: "in_network",
      lines: [{ dateOfService: "2026-07-08", code: "99213", diagnosisCodes: ["J02.9"], units: 1, charge: 28500, lineStatus: "Paid" }],
    },
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-0711-1182",
      processedDate: "2026-07-24",
      patient: "Priya Natarajan",
      provider: "Maple Street Family Medicine",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-07-08", service: "Office visit", code: "99213", benefitKey: "pcp_visit", billed: 28500, allowed: 14200, planPaid: 14200 })],
      remarks: [{ code: "N10", text: "Paid at the in-network benefit level. This is not a bill." }],
    },
    planRulesDoc([
      ["Primary care visit", "rhus.benefit.pcp_visit"],
      ["In-network cost sharing", "rhus.cost.in_network_no_cost_share"],
      ["In-network deductible", "rhus.cost.deductible.in_network"],
      ["Who files the claim", "rhus.structure.in_network_direct_billing"],
    ]),
  ],
  tasks: [
    choice(
      "t-doc-type",
      "What kind of document did the member receive?",
      [
        ["eob", "An Explanation of Benefits: the plan's record of how the claim was processed"],
        ["bill", "A bill from the doctor's office"],
        ["collections", "A collections notice"],
        ["premium", "A premium invoice from the plan"],
      ],
      ["eob"],
      { category: "eob_interpretation", points: 3, basis: [fact("doc-eob"), concept("eob")], expectation: "Recognizes the document as an EOB, not a bill.", missed: "The document is an EOB: it explains how the plan processed the claim. It's not a request for payment. Bills come from the provider." },
      "An EOB. It explains processing and isn't a bill.",
    ),
    choice(
      "t-billed-allowed",
      "What is the difference between the $285.00 and the $142.00 on the EOB?",
      [
        ["right", "$285 is the doctor's full charge; $142 is the amount the plan recognizes for an in-network visit"],
        ["owed", "$142 is what the member owes; $285 is what the plan paid"],
        ["two", "They are two separate visits"],
        ["paid", "$285 is what the plan paid; $142 is the member's deductible"],
      ],
      ["right"],
      { category: "eob_interpretation", points: 4, basis: [concept("billed-amount"), concept("allowed-amount"), concept("contracted-rate")], expectation: "Distinguishes the billed amount from the allowed amount.", missed: "Billed = the provider's full charge. Allowed = what the plan recognizes for the service (for in-network providers, typically the contracted rate). Confusing the two is the most common EOB mistake." },
      "Billed $285 is the charge; allowed $142 is what the plan recognizes.",
    ),
    amount(
      "t-owed",
      "According to the EOB, how much does the member owe for this visit?",
      0,
      { category: "eob_interpretation", points: 4, basis: [fact("doc-eob"), concept("member-responsibility")], expectation: "Reads member responsibility ($0.00), not the billed amount.", missed: "Member responsibility is $0.00. The plan paid the full $142 allowed amount. The $285 billed amount is not what the member owes." },
      "$0.00",
      { measures: "eob_member_responsibility" },
    ),
    amount(
      "t-discount",
      "How much of the billed charge is above the allowed amount (the network discount the member is not charged)?",
      14300,
      { category: "eob_interpretation", points: 3, basis: [fact("doc-eob"), concept("contracted-rate")], expectation: "Calculates billed − allowed = $143.00.", missed: "$285.00 − $142.00 = $143.00. For an in-network provider that difference is a contractual write-off, not a member charge." },
      "$143.00",
    ),
    choice(
      "t-why-zero",
      "Why is the member responsibility $0?",
      [
        ["plan", "In network, a covered PCP visit is paid at 100% with a $0 deductible and no provider copay"],
        ["deductible", "The member already met their deductible"],
        ["waived", "The doctor waived the charge"],
        ["denied", "The claim was denied, so nothing is owed"],
      ],
      ["plan"],
      { category: "plan_knowledge", points: 4, basis: [rule("rhus.benefit.pcp_visit"), rule("rhus.cost.in_network_no_cost_share"), rule("rhus.cost.deductible.in_network")], expectation: "Applies the official in-network rules.", missed: "Official rules: in-network PCP visits are covered at 100%, the in-network deductible is $0, and there is no in-network provider copay. The member had nothing to 'meet'." },
      "In-network PCP visits are paid at 100%, with a $0 deductible and no provider copay.",
    ),
    choice(
      "t-cpt",
      "Which code describes the service the doctor performed?",
      [["99213", "99213"], ["j029", "J02.9"], ["n10", "N10"], ["clm", "CLM-26-0711-1182"]],
      ["99213"],
      { category: "coding_understanding", points: 3, basis: [concept("cpt"), fact("doc-claim")], expectation: "Identifies the CPT code as the service.", missed: "CPT codes describe what was done. 99213 is the office visit. J02.9 is the diagnosis, N10 is a remark code, and the CLM number is the claim number." },
      "99213, the CPT code for the office visit.",
    ),
    choice(
      "t-icd",
      "What does J02.9 tell the plan?",
      [
        ["why", "Why the member was seen: a sore throat (the diagnosis)"],
        ["what", "What procedure was done"],
        ["where", "Where the visit took place"],
        ["how-much", "How much the visit cost"],
      ],
      ["why"],
      { category: "coding_understanding", points: 3, basis: [concept("icd10")], expectation: "Identifies the ICD-10 code as the reason for care.", missed: "ICD-10-CM codes describe why care was given. J02.9 is acute pharyngitis, the reason for the visit." },
      "The reason for the visit: acute pharyngitis.",
    ),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-processed", category: "claims_reasoning", points: 4, basis: [fact("doc-claim"), fact("doc-eob")], expectation: "States that the claim was processed and paid in full at the in-network level, that the EOB is the plan's record, and that nothing is due. No inconsistency.", missed: "Confirm the basics: claim status (paid), network (in), member responsibility ($0). Not every ticket hides an error. Saying so clearly is the job." },
        { id: "c-watch", category: "problem_solving", points: 3, basis: [concept("provider-statement"), concept("care-coordination")], expectation: "Tells the member what to watch for: if a statement from the practice arrives, compare it with the EOB, and contact support if it shows a balance.", missed: "Good navigators prevent the next ticket. Explain that the practice's bill (if any) should match the EOB's $0." },
      ],
      "The claim for the 07/08 visit (99213, J02.9) was paid in full at the in-network level: billed $285, allowed $142, plan paid $142, member responsibility $0. The letter is an EOB, not a bill. Nothing is inconsistent. If Maple Street sends a statement, it should show $0. Ask the member to send it if it shows any balance.",
    ),
    memberReply({
      accuracy: "States correctly that the letter is not a bill, that the plan paid the visit in full, and that the member owes $0 according to the EOB.",
      accuracyBasis: [fact("doc-eob")],
      promises: "Doesn't make blanket promises about future visits (e.g. 'everything is always free'). Sticks to what this EOB shows.",
      next: "Tells the member no action is needed, and to send any bill from the practice if one arrives.",
      empathy: "Reassures a member who is new to US insurance without being condescending.",
    }),
  ],
  debrief: {
    whatHappened:
      "Maple Street billed $285 for an in-network office visit. The plan recognized $142 (the in-network allowed amount) and paid all of it. The EOB shows $0 member responsibility. The member read the 'amount billed' line as a bill.",
    correctReasoning: [
      "The document is an EOB: it explains processing and is not a bill.",
      "Billed ($285) is the provider's charge. Allowed ($142) is what the plan recognizes. The $143 difference is a network write-off.",
      "Official rules: in-network PCP visits are covered at 100%, with a $0 deductible and no provider copay, so member responsibility is $0.",
      "CPT 99213 = what was done (office visit). ICD-10 J02.9 = why (sore throat).",
      "No discrepancy. The next step is just to compare any provider statement with the EOB.",
    ],
    modelMemberResponse:
      "Hi Priya, welcome, and great question! That letter is an Explanation of Benefits, not a bill. It shows how your plan handled your July visit. The doctor's full price was $285, but because they're in your plan's network, the plan's approved price is $142, and the plan paid all of it. The line that matters is 'you owe', and it's $0. So there's nothing to pay. If the doctor's office ever sends you a bill for this visit, send it to me and I'll check it against this letter.",
    conceptsToReview: ["eob", "billed-amount", "allowed-amount", "member-responsibility", "cpt", "icd10"],
  },
};

// =============================================================================
// CASE 02 · Foundation · Provider copay that the plan doesn't have
// =============================================================================
export const case02: SimulationCaseInput = {
  id: "case-02-copay-due",
  version: 1,
  portfolioNumber: 2,
  code: "CASE-02",
  title: "\"Copay due\": a charge the EOB doesn't support",
  summary: "A dermatology office bills a 'copay' after a visit the plan paid in full, and the member asks about their pharmacy charge too.",
  scenario: "In-network specialist visit with $0 EOB. The provider statement asks for a front-desk 'copay'. Pharmacy copay is correct.",
  recordingPriority: "medium",
  difficulty: "foundation",
  status: "ready",
  isSample: false,
  caseTypes: ["medical_billing", "eob_investigation", "coordination"],
  skills: ["billing_reconciliation", "inconsistency_detection", "member_responsibility", "provider_communication", "pharmacy_authorization", "plain_english", "cost_sharing"],
  knowledge: knowledge(
    ["rhus.benefit.specialist_visit", "rhus.cost.in_network_no_cost_share", "rhus.rx.retail"],
    ["eob", "provider-statement", "member-responsibility", "copayment", "contracted-rate", "pharmacy-prior-authorization", "cpt", "icd10", "care-coordination", "member-communication"],
  ),
  ticket: {
    channel: "email",
    receivedAt: "2026-07-15T09:05:00Z",
    memberMessage:
      "Hello, my dermatologist sent me a bill for $40 that says \"copay due\". I thought this plan didn't have copays? Also, the pharmacy charged me $10 for the cream she prescribed. Is that right, or should that be free too? And the pharmacist said if I want the brand-name version instead, it \"needs prior authorization\". What does that mean? Thanks, Marcus",
  },
  member: { name: "Marcus Bell", memberId: "RHU-31876-01", details: "Employee" },
  plan: RHUS_PLAN,
  provider: { name: "Clearview Dermatology", type: "Dermatology practice (fictional)", networkStatus: "in_network" },
  codes: [cpt("99203", "Office visit, new patient, low complexity."), icd("L70.0", "Acne vulgaris.")],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION, "The cream is a generic drug filled at a retail pharmacy as a 30-day supply."],
  documents: [
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-0613-0457",
      processedDate: "2026-06-27",
      patient: "Marcus Bell",
      provider: "Clearview Dermatology",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-06-12", service: "New patient visit", code: "99203", benefitKey: "specialist_visit", billed: 26000, allowed: 17500, planPaid: 17500 })],
      remarks: [{ code: "N10", text: "Paid at the in-network benefit level." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Clearview Dermatology",
      statementDate: "2026-07-08",
      accountNumber: "CVD-88213",
      lines: [{ dateOfService: "2026-06-12", description: "New patient office visit", code: "99203", charge: 26000 }],
      insurancePayments: 17500,
      adjustments: 8500,
      balanceDue: 4000,
      message: "Copay due at time of service: $40.00. Please remit.",
    },
    { id: "doc-rx", type: "note", title: "Pharmacy receipt", provenance: caseFact(), author: "Corner Pharmacy", date: "2026-06-12", body: "Tretinoin 0.025% cream (generic), 30-day supply. Plan paid: remainder. Patient paid: $10.00. Pharmacist note: brand-name equivalent rejected at the counter. Message: 'Prior authorization required'." },
    planRulesDoc([
      ["Specialist visit", "rhus.benefit.specialist_visit"],
      ["In-network cost sharing", "rhus.cost.in_network_no_cost_share"],
      ["Retail prescriptions", "rhus.rx.retail"],
    ]),
  ],
  tasks: [
    amount("t-eob-owed", "According to the EOB, what is the member responsibility for the visit?", 0, { category: "eob_interpretation", points: 4, basis: [fact("doc-eob"), concept("member-responsibility")], expectation: "Reads $0.00 from the EOB.", missed: "The EOB shows $0.00 member responsibility. The plan paid the full $175 allowed amount." }, "$0.00", { measures: "eob_member_responsibility" }),
    amount("t-bill-balance", "What balance is the provider statement asking the member to pay?", 4000, { category: "eob_interpretation", points: 2, basis: [fact("doc-bill")], expectation: "Reads the statement's balance due ($40.00).", missed: "The statement's balance due is $40.00, labelled as a copay." }, "$40.00"),
    choice(
      "t-compare",
      "How does the provider statement compare with the EOB?",
      [
        ["unsupported", "The statement asks for $40 that the EOB doesn't support (EOB member responsibility is $0)"],
        ["match", "They match: the member owes the $40 copay"],
        ["eob-wrong", "The EOB must be wrong because the office charges copays"],
        ["lower", "The statement asks for less than the EOB says"],
      ],
      ["unsupported"],
      { category: "eob_interpretation", points: 4, basis: [fact("doc-eob"), fact("doc-bill"), concept("provider-statement")], expectation: "Identifies the discrepancy between statement and EOB.", missed: "The provider's balance should equal the EOB member responsibility. Here the EOB says $0 and the statement asks for $40, so the statement is the document to question." },
      "The $40 isn't supported by the EOB.",
    ),
    choice(
      "t-plan-copays",
      "Under Remote Health USA, which in-network costs can carry a copay?",
      [
        ["rx", "Prescription drugs only ($10–$50)"],
        ["specialist", "Specialist visits"],
        ["all", "All office visits"],
        ["none", "Nothing at all, including prescriptions"],
      ],
      ["rx"],
      { category: "plan_knowledge", points: 4, basis: [rule("rhus.cost.in_network_no_cost_share")], expectation: "Knows that in network the only member cost is the prescription copay.", missed: "Official rule: in network there is no deductible, no coinsurance and no provider copay. The only exception is a $10–$50 prescription copay." },
      "Prescriptions only.",
    ),
    amount("t-rx", "Under the plan, what should a 30-day retail supply of a generic drug cost the member?", 1000, { category: "plan_knowledge", points: 3, basis: [rule("rhus.rx.retail"), fact("doc-rx")], expectation: "Applies the generic retail copay ($10).", missed: "Official rule: retail pharmacy, 30-day supply, generic drug = $10, no deductible. The $10 the member paid is correct." }, "$10.00"),
    choice(
      "t-brand",
      "The pharmacy says the brand-name version 'needs prior authorization'. What can you tell the member from the official sources?",
      [
        ["verify", "The sources list brand copays ($30 preferred / $50 non-preferred, 30-day retail, no deductible) but don't describe a pharmacy authorization process, so the requirement and process need verifying before advising"],
        ["never", "Pharmacy drugs never need authorization on this plan"],
        ["list", "It's on the official pre-authorization list A–T"],
        ["free", "Once authorized, brand-name drugs are free"],
      ],
      ["verify"],
      { category: "plan_knowledge", points: 3, basis: [rule("rhus.rx.retail"), concept("pharmacy-prior-authorization"), fact("doc-rx")], expectation: "States what the sources do say (brand copays) and flags what they don't (pharmacy authorization process).", missed: "The official rules list retail brand copays ($30 preferred, $50 non-preferred, no deductible), but nothing about pharmacy authorization. The A–T list is for medical services. Say what's sourced, and verify the rest." },
      "Brand copays are sourced; the pharmacy authorization process isn't, so verify.",
    ),
    selectAll(
      "t-codes",
      "Select every code that describes what was done at the visit.",
      [["99203", "99203"], ["l700", "L70.0"], ["n10", "N10"], ["cvd", "CVD-88213"]],
      ["99203"],
      { category: "coding_understanding", points: 3, basis: [concept("cpt"), concept("icd10"), fact("doc-eob")], expectation: "Selects only the CPT code.", missed: "Only 99203 (CPT) describes what was done. L70.0 is the diagnosis (why), N10 is a remark code, and CVD-88213 is the account number." },
      "Only 99203.",
    ),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-cause", category: "claims_reasoning", points: 4, basis: [fact("doc-bill"), fact("doc-eob"), rule("rhus.cost.in_network_no_cost_share")], expectation: "Identifies that the $40 isn't supported by the EOB or the plan rules (no in-network provider copay), and that it most likely reflects the office's standard front-desk practice.", missed: "The office is applying a charge the plan doesn't have. Under the official rules there is no in-network provider copay, and the EOB shows $0." },
        { id: "c-action", category: "problem_solving", points: 4, basis: [concept("care-coordination"), fact("doc-bill")], expectation: "Plans to contact Clearview's billing office with the EOB, ask them to remove the $40 balance, and ask for a refund if the member already paid it.", missed: "The fix is a billing correction by the provider, not a claim issue. Contact the billing office with the EOB in hand." },
        { id: "c-rx", category: "plan_knowledge", points: 2, basis: [rule("rhus.rx.retail"), fact("doc-rx"), concept("pharmacy-prior-authorization")], expectation: "Confirms that the $10 generic copay is correct, and explains that the brand-name request needs verification (the sources list the brand copay but no pharmacy authorization process).", missed: "Answer every question in the ticket. The $10 generic copay is correct, and the brand-name question is answered honestly with 'here's what's sourced, and I'll verify the rest'." },
      ],
      "The EOB shows the visit paid in full: allowed $175, member responsibility $0. Clearview's statement still asks for $40, labelled as a copay. That charge isn't supported: the plan has no in-network provider copay. It's most likely a front-desk default. Next step: contact Clearview's billing office with the EOB and ask them to zero the balance (or refund it if paid). The $10 pharmacy charge is correct: generic retail, 30-day supply. Brand name: the official rules list a $30 or $50 copay (preferred or non-preferred), but not the pharmacy authorization process, so verify it before advising.",
    ),
    memberReply({
      accuracy: "Says the visit was paid in full and the EOB shows $0, that the plan doesn't have in-network provider copays, and that the $10 prescription charge is correct.",
      accuracyBasis: [fact("doc-eob"), rule("rhus.cost.in_network_no_cost_share"), rule("rhus.rx.retail")],
      promises: "Doesn't promise a refund or guarantee the office will agree before confirming. Says what you're doing to fix it.",
      next: "Tells the member not to pay the $40 for now, and when you'll update them after contacting the office.",
    }),
  ],
  debrief: {
    whatHappened:
      "Clearview's visit was processed and paid in full at the in-network level (EOB: $0 member responsibility). The office's statement still asked for $40, labelled as a copay, most likely its standard front-desk practice. The pharmacy charged the plan's correct $10 generic copay.",
    correctReasoning: [
      "EOB member responsibility is $0. The statement asks for $40, so they don't match.",
      "Official rule: no deductible, coinsurance or provider copay in network. The only member cost is the $10–$50 prescription copay.",
      "The fix is a billing correction from the provider: contact their billing office with the EOB.",
      "Official rule: generic retail 30-day supply = $10, so the pharmacy charge is right.",
      "Brand-name 'needs prior authorization': the official rules list brand copays but not a pharmacy authorization process, so verify rather than guess.",
      "99203 = what was done (visit). L70.0 = why (acne).",
    ],
    modelMemberResponse:
      "Hi Marcus, thanks for checking before paying, that was the right move. I looked at how your plan processed the visit: it paid the dermatologist in full, and your statement from the plan shows you owe $0. Your plan doesn't have copays for in-network doctor visits, so that $40 bill doesn't match. Please don't pay it for now. I'm contacting Clearview's billing office today to ask them to correct it. Your $10 pharmacy charge is right: generic prescriptions on your plan are $10 for a 30-day supply. For the brand-name cream, I'll check what approval is needed and how it works, since the pharmacy's message doesn't tell us. I'll update you on both by Thursday.",
    conceptsToReview: ["provider-statement", "member-responsibility", "copayment"],
  },
};
