import type { SimulationCaseInput } from "@/domain/case";
import { caseFact } from "@/domain/provenance";
import {
  DOCS_ASSUMPTION, FICTION_ASSUMPTION, INVESTIGATION_PROMPT, RHUS_PLAN, amount, choice, concept, cpt, eobLine, fact, icd,
  investigation, knowledge, memberReply, planRulesDoc, rule, selectAll,
} from "./helpers";

// =============================================================================
// CASE 03 · Foundation · Bill arrives while the claim is pending
// =============================================================================
export const case03: SimulationCaseInput = {
  id: "case-03-pending-claim",
  version: 1,
  portfolioNumber: 3,
  code: "CASE-03",
  title: "A $480 bill for a claim that isn't finished",
  summary: "A physical therapy clinic bills the member while the claim is still pended for records.",
  scenario: "In-network PT. The claim is pended for provider records, yet the clinic transfers the balance to the patient. Member considers stopping therapy.",
  recordingPriority: "medium",
  difficulty: "foundation",
  status: "ready",
  isSample: false,
  caseTypes: ["claims_investigation", "medical_billing", "coding"],
  skills: ["claim_status", "billing_reconciliation", "provider_communication", "cpt", "icd10", "member_communication"],
  knowledge: knowledge(
    ["rhus.benefit.physical_therapy", "rhus.cost.in_network_no_cost_share", "rhus.structure.in_network_direct_billing", "rhus.structure.bywater_tpa"],
    ["claims-lifecycle", "claim-statuses", "adjudication", "provider-statement", "eob", "cpt", "icd10", "care-coordination", "member-communication"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-09-21T13:22:00Z",
    memberMessage:
      "Hi. I've done 3 physical therapy sessions for my shoulder and the clinic already sent me a bill for $480. My doctor referred me there. Does my plan not cover PT?? I have 6 more sessions booked and honestly I'm thinking of cancelling them.",
  },
  member: { name: "Dana Kowalski", memberId: "RHU-11590-02", details: "Spouse of employee" },
  plan: RHUS_PLAN,
  provider: { name: "Riverbend Physical Therapy", type: "Outpatient physical therapy clinic (fictional)", networkStatus: "in_network" },
  codes: [
    cpt("97161", "Physical therapy evaluation, low complexity."),
    cpt("97110", "Therapeutic exercise, per 15 minutes."),
    icd("M25.511", "Pain in right shoulder."),
  ],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION],
  documents: [
    {
      id: "doc-claim-eval",
      type: "claim",
      title: "Claim record: evaluation (07/28)",
      provenance: caseFact(),
      claimNumber: "CLM-26-0730-2204",
      status: "processed_paid",
      receivedDate: "2026-07-30",
      processedDate: "2026-08-12",
      billingProvider: "Riverbend Physical Therapy",
      networkStatus: "in_network",
      lines: [{ dateOfService: "2026-07-28", code: "97161", diagnosisCodes: ["M25.511"], units: 1, charge: 21000, lineStatus: "Paid" }],
    },
    {
      id: "doc-claim-visits",
      type: "claim",
      title: "Claim record: therapy visits (08/04–08/18)",
      provenance: caseFact(),
      claimNumber: "CLM-26-0821-3391",
      status: "pended",
      receivedDate: "2026-08-21",
      billingProvider: "Riverbend Physical Therapy",
      networkStatus: "in_network",
      lines: [
        { dateOfService: "2026-08-04", code: "97110", diagnosisCodes: ["M25.511"], units: 2, charge: 16000, lineStatus: "Pended: records requested from provider (plan of care), 08/28" },
        { dateOfService: "2026-08-11", code: "97110", diagnosisCodes: ["M25.511"], units: 2, charge: 16000, lineStatus: "Pended: records requested from provider (plan of care), 08/28" },
        { dateOfService: "2026-08-18", code: "97110", diagnosisCodes: ["M25.511"], units: 2, charge: 16000, lineStatus: "Pended: records requested from provider (plan of care), 08/28" },
      ],
    },
    {
      id: "doc-eob-eval",
      type: "eob",
      title: "Explanation of Benefits: evaluation (07/28)",
      provenance: caseFact(),
      claimNumber: "CLM-26-0730-2204",
      processedDate: "2026-08-12",
      patient: "Dana Kowalski",
      provider: "Riverbend Physical Therapy",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-07-28", service: "PT evaluation", code: "97161", benefitKey: "physical_therapy", billed: 21000, allowed: 15000, planPaid: 15000 })],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Riverbend Physical Therapy",
      statementDate: "2026-09-18",
      accountNumber: "RPT-40571",
      lines: [
        { dateOfService: "2026-08-04", description: "Therapeutic exercise x2", code: "97110", charge: 16000 },
        { dateOfService: "2026-08-11", description: "Therapeutic exercise x2", code: "97110", charge: 16000 },
        { dateOfService: "2026-08-18", description: "Therapeutic exercise x2", code: "97110", charge: 16000 },
      ],
      insurancePayments: 0,
      adjustments: 0,
      balanceDue: 48000,
      message: "Insurance has not paid within 30 days. Balance transferred to patient.",
    },
    planRulesDoc([
      ["Physical therapy", "rhus.benefit.physical_therapy"],
      ["In-network cost sharing", "rhus.cost.in_network_no_cost_share"],
      ["Who files the claim", "rhus.structure.in_network_direct_billing"],
      ["Claims administration", "rhus.structure.bywater_tpa"],
    ]),
  ],
  tasks: [
    choice(
      "t-status",
      "What is the status of the claim for the three therapy visits?",
      [
        ["pended", "Pended: the plan asked the provider for records and is waiting"],
        ["denied", "Denied: PT isn't covered"],
        ["paid", "Paid, and the clinic is billing the remainder"],
        ["missing", "Never received by the plan"],
      ],
      ["pended"],
      { category: "claims_reasoning", points: 4, basis: [fact("doc-claim-visits"), concept("claim-statuses")], expectation: "Reads the pended status and its reason.", missed: "The claim is pended: records (the plan of care) were requested from the provider on 08/28. It hasn't been decided, let alone denied." },
      "Pended for provider records.",
    ),
    choice(
      "t-owe-now",
      "Based on the documents, what does the member owe for the three visits right now?",
      [
        ["undetermined", "Not determined yet: the claim hasn't been processed, so there is no EOB for these visits"],
        ["480", "$480, the statement balance"],
        ["zero-final", "$0, guaranteed"],
        ["160", "$160, one visit"],
      ],
      ["undetermined"],
      { category: "claims_reasoning", points: 4, basis: [fact("doc-claim-visits"), concept("adjudication")], expectation: "Recognizes that member responsibility is set at adjudication, so nothing is established yet.", missed: "Member responsibility comes from the EOB after adjudication. With the claim pended, the $480 statement is premature, and '$0 guaranteed' would be an unsupported promise." },
      "Not determined yet.",
    ),
    amount("t-eval-owed", "For comparison: what was the member responsibility on the EOB for the evaluation visit?", 0, { category: "eob_interpretation", points: 3, basis: [fact("doc-eob-eval")], expectation: "Reads $0.00 from the evaluation EOB.", missed: "The 07/28 evaluation EOB shows $0.00 member responsibility. The same clinic's first claim was paid in full." }, "$0.00", { measures: "eob_member_responsibility" }),
    choice(
      "t-benefit",
      "What do the official plan rules say about in-network physical therapy?",
      [
        ["covered", "Covered at 100% in network, including virtual visits. The source states no pre-authorization requirement."],
        ["pa", "Covered only with pre-authorization"],
        ["limit", "Limited to 20 visits"],
        ["oon", "Paid at 70% after the deductible"],
      ],
      ["covered"],
      { category: "plan_knowledge", points: 4, basis: [rule("rhus.benefit.physical_therapy"), rule("rhus.cost.in_network_no_cost_share")], expectation: "States the PT benefit accurately without inventing limits or requirements.", missed: "Official rule: physical therapy is 100% in network (70% after deductible out of network), including virtual visits. No pre-authorization requirement or visit limit is stated. The 20-visit limit belongs to acupuncture and chiropractic." },
      "100% in network; no pre-authorization or visit limit stated.",
    ),
    choice(
      "t-who",
      "Who needs to act to move the claim forward?",
      [["provider", "Riverbend: send the requested plan of care"], ["member", "The member: file a new claim"], ["employer", "The employer"], ["nobody", "Nobody: wait for it to be denied"]],
      ["provider"],
      { category: "problem_solving", points: 3, basis: [fact("doc-claim-visits"), rule("rhus.structure.in_network_direct_billing"), concept("care-coordination")], expectation: "Identifies the provider as the party that must respond.", missed: "The records request went to the provider. In-network providers bill the plan directly, so the member doesn't file anything. Riverbend needs to send the plan of care." },
      "Riverbend Physical Therapy.",
    ),
    selectAll(
      "t-codes",
      "Select every code on these claims that describes a service performed.",
      [["97161", "97161"], ["97110", "97110"], ["m25511", "M25.511"], ["rpt", "RPT-40571"]],
      ["97161", "97110"],
      { category: "coding_understanding", points: 4, basis: [concept("cpt"), concept("icd10"), fact("doc-claim-visits")], expectation: "Selects both CPT codes and not the diagnosis.", missed: "97161 (evaluation) and 97110 (therapeutic exercise) are CPT service codes. M25.511 is the diagnosis. RPT-40571 is the account number." },
      "97161 and 97110.",
    ),
    choice(
      "t-icd",
      "What does M25.511 tell the claims reviewer?",
      [["why", "Why therapy is being done: right shoulder pain"], ["what", "Which exercises were performed"], ["units", "How many units were billed"], ["auth", "That therapy was pre-approved"]],
      ["why"],
      { category: "coding_understanding", points: 3, basis: [concept("icd10")], expectation: "Identifies the diagnosis as the reason for care.", missed: "ICD-10 M25.511 (pain in right shoulder) is the reason for the therapy. It supports why 97110 was performed." },
      "The reason for care: right shoulder pain.",
    ),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-premature", category: "claims_reasoning", points: 4, basis: [fact("doc-claim-visits"), fact("doc-bill"), concept("provider-statement")], expectation: "Explains that the statement is premature: the claim is pended for provider records, member responsibility isn't determined, and the clinic's earlier claim was paid in full.", missed: "The key insight is timing. The bill arrived before adjudication, so there is nothing to reconcile it against yet." },
        { id: "c-actions", category: "problem_solving", points: 4, basis: [concept("care-coordination"), rule("rhus.structure.bywater_tpa")], expectation: "Plans to: ask Riverbend to send the plan of care and hold patient billing until the EOB issues, and check the claim status with the claims administrator after the records are sent.", missed: "Coordinate both sides. The provider must respond to the records request. The administrator (Bywater) processes the claim once the records arrive." },
        { id: "c-benefit", category: "plan_knowledge", points: 2, basis: [rule("rhus.benefit.physical_therapy")], expectation: "Notes that in-network PT is covered at 100% under the plan's rules, without guaranteeing how this claim will be decided.", missed: "Reassure with the plan rule, but don't promise the claim's outcome while it's pended." },
      ],
      "The 08/04–08/18 claim (3 × 97110 for M25.511) is pended: on 08/28 the plan asked Riverbend for the plan of care. No EOB exists yet, so member responsibility isn't determined. Riverbend transferred $480 to the patient after 30 days, which is premature. The evaluation claim from the same clinic was paid in full ($0). Next steps: ask Riverbend to send the records and hold the patient balance, then confirm with the administrator that the records were received. Under the plan, in-network PT is covered at 100%, with no pre-authorization or visit limit stated.",
    ),
    memberReply({
      accuracy: "Says the claim is still being processed, waiting on paperwork from the clinic, so the $480 isn't a final amount. Notes the evaluation visit was paid in full.",
      accuracyBasis: [fact("doc-claim-visits"), fact("doc-eob-eval")],
      promises: "Doesn't guarantee the claim will pay or that the final amount is $0. Can say in-network PT is covered under the plan's rules.",
      next: "Asks the member to hold off paying the $480 while you sort it out. Leaves the decision about attending sessions to the member and their therapist, noting that PT is a covered benefit. Gives a follow-up time.",
      nextBasis: [rule("rhus.benefit.physical_therapy")],
    }),
  ],
  debrief: {
    whatHappened:
      "Riverbend's claim for three therapy visits was pended on 08/28 waiting for the plan of care. Before the claim could be processed, Riverbend's system moved the $480 balance to the patient. The clinic's earlier evaluation claim was paid in full.",
    correctReasoning: [
      "Pended isn't denied: the claim is waiting on provider records.",
      "No EOB means member responsibility isn't established. The statement is premature.",
      "The provider must send the plan of care. The member doesn't need to file anything for in-network care.",
      "Official rule: PT is 100% in network, including virtual visits, with no pre-authorization or visit limit stated.",
      "97161/97110 = what was done. M25.511 = why.",
    ],
    modelMemberResponse:
      "Hi Dana, I'm sorry, a surprise bill in the middle of treatment is stressful. Here's what I found: your plan hasn't finished processing these three visits yet. It's waiting for some paperwork from the clinic, so that $480 isn't a final amount. Your first visit there was paid in full by the plan. Physical therapy with an in-network clinic is a covered benefit under your plan, so please don't pay the $480 for now. I'm contacting Riverbend today to ask them to send the paperwork and pause the bill. Whether to keep your sessions is your call with your therapist. I'll update you by Wednesday.",
    conceptsToReview: ["claim-statuses", "adjudication", "provider-statement"],
  },
};

// =============================================================================
// CASE 04 · Foundation · CT with pre-authorization done right
// =============================================================================
export const case04: SimulationCaseInput = {
  id: "case-04-ct-authorized",
  version: 1,
  portfolioNumber: 4,
  code: "CASE-04",
  title: "Approved CT, scary-looking EOB",
  summary: "A member worries about a $3,150 figure after a pre-authorized, in-network CT, and about a '$0.00' statement.",
  scenario: "Pre-authorization required, obtained and linked. The claim is paid correctly. Member confuses the billed amount with the amount owed.",
  recordingPriority: "high",
  difficulty: "foundation",
  status: "ready",
  isSample: false,
  caseTypes: ["prior_authorization", "eob_investigation", "coding"],
  skills: ["prior_auth", "eob_reading", "allowed_amount", "cpt", "icd10", "plain_english"],
  knowledge: knowledge(
    ["rhus.benefit.diagnostic_ct", "rhus.pa.list.k", "rhus.pa.provider_usually_requests", "rhus.pa.member_must_confirm", "rhus.cost.in_network_no_cost_share"],
    ["prior-authorization", "authorization-linking", "eob", "member-responsibility", "billed-amount", "allowed-amount", "contracted-rate", "provider-statement", "cpt", "icd10", "medical-necessity", "member-communication"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-10-01T18:03:00Z",
    memberMessage:
      "Hi, I had a CT scan in September after an ER doctor told me to follow up on stomach pain. My plan sent a statement that says $3,150?! My doctor's office said they got approval beforehand. Did something go wrong? The imaging place also sent a statement but it says $0.00. Is that a mistake?",
  },
  member: { name: "Tomás Herrera", memberId: "RHU-27704-01", details: "Employee" },
  plan: RHUS_PLAN,
  provider: { name: "Summit Imaging", type: "Outpatient imaging center (fictional)", networkStatus: "in_network" },
  codes: [cpt("74177", "CT scan of the abdomen and pelvis with contrast."), icd("R10.31", "Right lower quadrant abdominal pain.")],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION],
  documents: [
    {
      id: "doc-auth",
      type: "authorization",
      title: "Authorization record",
      provenance: caseFact(),
      authNumber: "AUTH-2026-091877",
      status: "approved",
      service: "CT abdomen and pelvis with contrast",
      codes: ["74177"],
      diagnosisCodes: ["R10.31"],
      requestingProvider: "Dr. Lena Ortiz (Internal medicine)",
      servicingProvider: "Summit Imaging",
      requestedDate: "2026-09-02",
      decisionDate: "2026-09-03",
      validFrom: "2026-09-03",
      validTo: "2026-10-31",
      notes: "Approved.",
      requirement: { benefitKey: "diagnostic_ct", required: true },
    },
    {
      id: "doc-claim",
      type: "claim",
      title: "Claim record",
      provenance: caseFact(),
      claimNumber: "CLM-26-0912-6610",
      status: "processed_paid",
      receivedDate: "2026-09-12",
      processedDate: "2026-09-24",
      billingProvider: "Summit Imaging",
      networkStatus: "in_network",
      authorizationNumberOnClaim: "AUTH-2026-091877",
      lines: [{ dateOfService: "2026-09-09", code: "74177", diagnosisCodes: ["R10.31"], units: 1, charge: 315000, lineStatus: "Paid" }],
    },
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-0912-6610",
      processedDate: "2026-09-24",
      patient: "Tomás Herrera",
      provider: "Summit Imaging",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-09-09", service: "CT abdomen/pelvis", code: "74177", benefitKey: "diagnostic_ct", billed: 315000, allowed: 98000, planPaid: 98000 })],
      remarks: [{ code: "A1", text: "Authorization AUTH-2026-091877 applied." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Summit Imaging",
      statementDate: "2026-09-28",
      accountNumber: "SI-220913",
      lines: [{ dateOfService: "2026-09-09", description: "CT abd/pelvis w/ contrast", code: "74177", charge: 315000 }],
      insurancePayments: 98000,
      adjustments: 217000,
      balanceDue: 0,
      message: "Account paid in full. No payment needed.",
    },
    planRulesDoc([
      ["CT benefit", "rhus.benefit.diagnostic_ct"],
      ["Pre-authorization list", "rhus.pa.list.k"],
      ["Who requests pre-authorization", "rhus.pa.provider_usually_requests"],
      ["Member's responsibility", "rhus.pa.member_must_confirm"],
      ["In-network cost sharing", "rhus.cost.in_network_no_cost_share"],
    ]),
  ],
  tasks: [
    choice(
      "t-pa-required",
      "Did this CT require pre-authorization under the plan?",
      [["yes", "Yes: CT is on the official pre-authorization list (item K)"], ["no", "No: only MRI needs pre-authorization"], ["oon", "Only if the provider is out of network"], ["er", "No, because an ER doctor recommended it"]],
      ["yes"],
      { category: "prior_authorization", points: 4, basis: [rule("rhus.pa.list.k"), rule("rhus.benefit.diagnostic_ct")], expectation: "Knows CT requires pre-authorization.", missed: "Official rule: pre-authorization list item K, 'Diagnostic testing (MRI/PET/CT)'. A CT ordered after an ER visit is still a scheduled outpatient scan." },
      "Yes, list item K.",
    ),
    selectAll(
      "t-pa-match",
      "Select every statement that is true about the authorization and the claim.",
      [
        ["cpt", "The authorized CPT (74177) matches the claim"],
        ["dx", "The authorized diagnosis (R10.31) matches the claim"],
        ["dos", "The date of service (09/09) is inside the validity window"],
        ["authno", "The authorization number appears on the claim"],
        ["mri", "The authorization was for an MRI, not a CT"],
      ],
      ["cpt", "dx", "dos", "authno"],
      { category: "prior_authorization", points: 4, basis: [fact("doc-auth"), fact("doc-claim"), concept("authorization-linking")], expectation: "Confirms that the authorization was required, obtained, matching, and linked.", missed: "Check all four: required, obtained, matches (code/diagnosis/date/provider), linked (number on the claim). Here every check passes." },
      "Code, diagnosis and date match, and the authorization number is on the claim.",
    ),
    amount("t-owed", "According to the EOB, how much does the member owe?", 0, { category: "eob_interpretation", points: 4, basis: [fact("doc-eob"), concept("member-responsibility")], expectation: "Reads $0.00 member responsibility.", missed: "The EOB shows $0.00 member responsibility. The $3,150 is the billed charge." }, "$0.00", { measures: "eob_member_responsibility" }),
    amount("t-adjustment", "How much did Summit Imaging write off as a contractual adjustment?", 217000, { category: "eob_interpretation", points: 3, basis: [fact("doc-bill"), fact("doc-eob"), concept("contracted-rate")], expectation: "Finds $2,170.00 (billed $3,150 − allowed $980).", missed: "Billed $3,150 − allowed $980 = $2,170. The statement shows that as an adjustment. An in-network provider writes off the amount above the contracted rate." }, "$2,170.00"),
    choice(
      "t-statement",
      "Is the $0.00 statement from Summit Imaging a mistake?",
      [["consistent", "No: it agrees with the EOB (plan paid the allowed amount; the rest was written off)"], ["owes-3150", "Yes: the member owes $3,150"], ["owes-980", "Yes: the member owes $980"], ["unknown", "Can't tell without calling the provider"]],
      ["consistent"],
      { category: "eob_interpretation", points: 3, basis: [fact("doc-bill"), fact("doc-eob"), concept("provider-statement")], expectation: "Reconciles the statement with the EOB.", missed: "Insurance paid $980 plus adjustment $2,170 = $3,150 charge, leaving $0. That matches the EOB's $0 member responsibility." },
      "Not a mistake. It matches the EOB.",
    ),
    choice(
      "t-cpt",
      "Which code is the procedure?",
      [["74177", "74177"], ["r1031", "R10.31"], ["a1", "A1"], ["auth", "AUTH-2026-091877"]],
      ["74177"],
      { category: "coding_understanding", points: 3, basis: [concept("cpt")], expectation: "Identifies 74177 as the service.", missed: "74177 is the CPT code for the CT. R10.31 is the diagnosis, A1 is a remark code, and AUTH-… is the authorization number." },
      "74177.",
    ),
    choice(
      "t-icd",
      "Does the diagnosis on the claim make sense as the reason for this CT?",
      [["yes", "Yes: right lower abdominal pain is a plausible reason for an abdomen/pelvis CT"], ["no-proc", "No: R10.31 is a procedure code"], ["mismatch", "No: it's an obvious mismatch that needs investigation"], ["irrelevant", "Diagnosis codes don't matter for claims"]],
      ["yes"],
      { category: "coding_understanding", points: 3, basis: [concept("icd10"), concept("medical-necessity")], expectation: "Recognizes that the diagnosis supports the procedure (no mismatch).", missed: "The ICD-10 code (why) should plausibly support the CPT (what). Abdominal pain supports an abdominal CT." },
      "Yes. The diagnosis supports the scan.",
    ),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-correct", category: "claims_reasoning", points: 4, basis: [fact("doc-claim"), fact("doc-eob"), fact("doc-auth")], expectation: "Concludes the claim was processed correctly: the required authorization was obtained and linked, the claim was paid at 100% in network, and $0 is owed. The statement agrees.", missed: "Sometimes the finding is 'nothing is wrong', and saying so with evidence is a skill. Every document agrees." },
        { id: "c-explain", category: "plan_knowledge", points: 3, basis: [rule("rhus.cost.in_network_no_cost_share"), concept("billed-amount"), concept("allowed-amount")], expectation: "Explains why the large figure isn't owed: billed vs. allowed, and in-network 100% coverage.", missed: "The member's fear comes from the billed amount. Explain billed vs. allowed and the in-network rule." },
        { id: "c-confirm", category: "prior_authorization", points: 2, basis: [rule("rhus.pa.member_must_confirm"), rule("rhus.pa.provider_usually_requests")], expectation: "Notes that the member did the right thing by confirming the approval, and that future MRI/CT/PET scans need their own pre-authorization.", missed: "Official rule: the member is responsible for confirming pre-authorization, and the provider usually requests it. Reinforce the habit." },
      ],
      "CT 74177 for R10.31 required pre-authorization (list item K). AUTH-2026-091877 was approved 09/03, valid through 10/31, for the same code, diagnosis and facility, and the number is on the claim. The claim was paid at the in-network level: billed $3,150, allowed $980, plan paid $980, member responsibility $0. Summit's statement shows the $2,170 adjustment and a $0 balance, which matches the EOB. Nothing is wrong. Reassure the member and remind them that future advanced imaging needs its own approval.",
    ),
    memberReply({
      accuracy: "Says correctly that nothing went wrong: the scan was pre-approved, the plan paid it, the member owes $0, and both statements agree.",
      accuracyBasis: [fact("doc-eob"), fact("doc-auth"), fact("doc-bill")],
      promises: "Doesn't overgeneralize (e.g. 'all scans are always free'). Notes that future scans like this need their own approval.",
      next: "Tells the member no payment is needed and gives a simple tip for next time.",
      nextBasis: [rule("rhus.pa.member_must_confirm")],
    }),
  ],
  debrief: {
    whatHappened:
      "Everything worked as designed. Dr. Ortiz obtained pre-authorization for the CT, Summit put the authorization number on the claim, and the plan paid the in-network allowed amount in full. The member saw the $3,150 billed amount on the EOB and assumed it was owed.",
    correctReasoning: [
      "Official rule: CT requires pre-authorization (list item K). It was required, obtained, matching and linked.",
      "Billed $3,150 vs. allowed $980: the plan paid the allowed amount and the provider wrote off $2,170.",
      "Official rules: in-network diagnostic testing is 100%, so member responsibility is $0.",
      "The provider's $0 statement agrees with the EOB.",
      "74177 = what (CT). R10.31 = why (abdominal pain). They're consistent.",
    ],
    modelMemberResponse:
      "Hi Tomás, good news: nothing went wrong. Your doctor got the pre-approval, and the imaging center used it. The $3,150 is the imaging center's full price, but because they're in your plan's network, the plan's approved price is $980, and your plan paid all of it. Your plan's statement shows you owe $0, and the imaging center's $0.00 statement matches. That's correct, not a mistake. You don't need to pay anything. One tip for the future: scans like CT, MRI or PET always need their own pre-approval, so checking with your doctor's office first, like you did, is exactly right.",
    conceptsToReview: ["prior-authorization", "authorization-linking", "billed-amount", "allowed-amount"],
  },
};
