import type { SimulationCaseInput } from "@/domain/case";
import { caseFact } from "@/domain/provenance";
import {
  DOCS_ASSUMPTION, FICTION_ASSUMPTION, INVESTIGATION_PROMPT, RHUS_PLAN, amount, choice, concept, cpt, eobLine, fact, icd,
  investigation, knowledge, knownVsUnknown, memberReply, planRulesDoc, rule, selectAll,
} from "./helpers";

// =============================================================================
// CASE 07 · Intermediate · In network or not? Billing-entity mismatch
// =============================================================================
export const case07: SimulationCaseInput = {
  id: "case-07-network-mismatch",
  version: 1,
  portfolioNumber: 7,
  code: "CASE-07",
  title: "\"The directory said in-network!\"",
  summary: "A cardiologist listed in the Cigna directory, but the claim came in under a different billing entity and was processed out of network.",
  scenario: "The claim was processed out of network ($380 to the deductible), and the provider bills $520. The directory lists the doctor in network under a different group and tax ID. Needs verification before anyone tells the member what they owe.",
  recordingPriority: "high",
  difficulty: "intermediate",
  status: "ready",
  isSample: false,
  caseTypes: ["claims_investigation", "eob_investigation", "coordination"],
  skills: ["network_status", "member_responsibility", "balance_billing", "inconsistency_detection", "claim_correction", "provider_communication"],
  knowledge: knowledge(
    ["rhus.structure.cigna_ppo_network", "rhus.benefit.specialist_visit", "rhus.cost.in_network_no_cost_share", "rhus.cost.deductible.out_of_network", "rhus.cost.coinsurance.out_of_network", "rhus.cost.balance_billing", "rhus.cost.deductible.rules"],
    ["network", "deductible", "balance-billing", "allowed-amount", "claim-correction", "provider-statement", "eob", "icd10", "cpt"],
  ),
  ticket: {
    channel: "email",
    receivedAt: "2026-07-09T08:31:00Z",
    memberMessage:
      "Hi, I checked the Cigna directory before booking and Dr. Shah was listed as in-network. Now the EOB says \"out-of-network\" and the cardiology office wants $520. I did everything right. Why is this happening? — Sam",
  },
  member: { name: "Sam Okafor", memberId: "RHU-52231-01", details: "Employee. No other out-of-network claims this year." },
  plan: RHUS_PLAN,
  provider: { name: "Dr. Mira Shah (cardiology)", type: "Cardiologist (fictional); network status under investigation", networkStatus: "unknown" },
  codes: [cpt("99204", "Office visit, new patient, moderate complexity."), icd("R00.2", "Palpitations.")],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION],
  documents: [
    {
      id: "doc-claim",
      type: "claim",
      title: "Claim record",
      provenance: caseFact(),
      claimNumber: "CLM-26-0606-5150",
      status: "processed_paid",
      receivedDate: "2026-06-06",
      processedDate: "2026-06-19",
      billingProvider: "Heartline Cardiology Associates LLC (tax ID ••9083)",
      renderingProvider: "Dr. Mira Shah",
      networkStatus: "out_of_network",
      lines: [{ dateOfService: "2026-06-03", code: "99204", diagnosisCodes: ["R00.2"], units: 1, charge: 52000, lineStatus: "Processed out of network" }],
    },
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-0606-5150",
      processedDate: "2026-06-19",
      patient: "Sam Okafor",
      provider: "Heartline Cardiology Associates LLC",
      networkStatus: "out_of_network",
      lines: [eobLine({ dateOfService: "2026-06-03", service: "New patient visit", code: "99204", benefitKey: "specialist_visit", billed: 52000, allowed: 38000, deductible: 38000, memberResponsibility: 38000, remarkCodes: ["N52"] })],
      remarks: [{ code: "N52", text: "Billing provider is not in network. Out-of-network deductible applied. Provider may bill you for amounts above the allowed amount." }],
    },
    { id: "doc-directory", type: "note", title: "Network directory lookup (by you, 07/09)", provenance: caseFact(), author: "Care Navigator", date: "2026-07-09", body: "Cigna PPO directory: Dr. Mira Shah, cardiology, practicing with Heartline Cardiology Group (tax ID ••4471). Listed in network, effective 01/01/2025. No listing found for 'Heartline Cardiology Associates LLC' (tax ID ••9083)." },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Heartline Cardiology Associates LLC",
      statementDate: "2026-07-01",
      accountNumber: "HCA-19022",
      lines: [{ dateOfService: "2026-06-03", description: "New patient visit", code: "99204", charge: 52000 }],
      insurancePayments: 0,
      adjustments: 0,
      balanceDue: 52000,
    },
    planRulesDoc([
      ["Network", "rhus.structure.cigna_ppo_network"],
      ["Specialist visit", "rhus.benefit.specialist_visit"],
      ["In-network cost sharing", "rhus.cost.in_network_no_cost_share"],
      ["Out-of-network deductible", "rhus.cost.deductible.out_of_network"],
      ["Out-of-network coinsurance", "rhus.cost.coinsurance.out_of_network"],
      ["Balance billing", "rhus.cost.balance_billing"],
    ]),
  ],
  tasks: [
    choice("t-level", "At what level was the claim processed?", [["oon", "Out of network: the allowed amount was applied to the out-of-network deductible"], ["in", "In network at 100%"], ["denied", "Denied"], ["pended", "Pended"]], ["oon"], { category: "claims_reasoning", points: 3, basis: [fact("doc-eob"), fact("doc-claim")], expectation: "Reads the network level and what it did.", missed: "The claim and EOB show out-of-network processing: the $380 allowed amount went to the deductible, and the plan paid $0." }, "Out of network."),
    amount("t-deductible", "How much of the member's $1,000 out-of-network deductible did this claim use?", 38000, { category: "eob_interpretation", points: 3, basis: [fact("doc-eob"), rule("rhus.cost.deductible.out_of_network")], expectation: "Reads $380.00 applied to the deductible.", missed: "With no earlier out-of-network claims, the whole $380 allowed amount went to the $1,000 out-of-network deductible." }, "$380.00"),
    amount("t-if-in", "If the claim had been processed in network, what would the member responsibility have been?", 0, { category: "plan_knowledge", points: 4, basis: [rule("rhus.benefit.specialist_visit"), rule("rhus.cost.in_network_no_cost_share")], expectation: "Applies the official in-network rule ($0).", missed: "Official rules: in-network specialist visits are covered at 100%, with no deductible or provider copay, so $0." }, "$0.00"),
    amount("t-balance", "How much of the provider's $520 balance is above the plan's allowed amount (the balance-billed portion)?", 14000, { category: "eob_interpretation", points: 3, basis: [fact("doc-bill"), fact("doc-eob"), rule("rhus.cost.balance_billing")], expectation: "Calculates $520 − $380 = $140.", missed: "Balance due $520 = $380 (EOB member responsibility) + $140 above the allowed amount. Out of network, that $140 is possible balance billing." }, "$140.00"),
    selectAll(
      "t-clues",
      "Which facts point to a possible network or billing-entity problem? Select all that apply.",
      [["dir", "The directory lists Dr. Shah in network with Heartline Cardiology Group (tax ID ••4471)"], ["entity", "The claim was billed by Heartline Cardiology Associates LLC (tax ID ••9083)"], ["dx", "The diagnosis code is wrong"], ["er", "The member went to an emergency room"]],
      ["dir", "entity"],
      { category: "claims_reasoning", points: 4, basis: [fact("doc-directory"), fact("doc-claim")], expectation: "Spots the billing-entity/tax ID difference.", missed: "Network status attaches to the billing entity. The doctor is in network under one group, but the claim came from a different entity that isn't listed." },
      "The directory listing and the different billing entity.",
    ),
    choice("t-next", "What is the best next step?", [["verify", "Verify with the practice which entity should have billed, and if it was billed under the wrong one, ask for a corrected claim so the administrator can reprocess"], ["owe", "Tell the member they owe $520"], ["appeal", "File an appeal immediately"], ["promise", "Tell the member it will be paid at 100%"]], ["verify"], { category: "problem_solving", points: 3, basis: [concept("claim-correction"), concept("care-coordination"), fact("doc-directory")], expectation: "Chooses verification and correction over conclusions.", missed: "Neither 'you owe $520' nor 'it'll be paid in full' is established. A billing-entity error is fixed by a corrected claim, after verification." }, "Verify the entity, then corrected claim and reprocessing if appropriate."),
    choice("t-dx", "Which code explains why the member saw the cardiologist?", [["r002", "R00.2"], ["99204", "99204"], ["n52", "N52"], ["tax", "••9083"]], ["r002"], { category: "coding_understanding", points: 3, basis: [concept("icd10")], expectation: "Identifies the ICD-10 diagnosis.", missed: "R00.2 (palpitations) is the reason for the visit. 99204 is the visit itself (CPT)." }, "R00.2."),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-entity", category: "claims_reasoning", points: 4, basis: [fact("doc-directory"), fact("doc-claim"), rule("rhus.structure.cigna_ppo_network")], expectation: "Identifies that Dr. Shah is listed in network under Heartline Cardiology Group, but the claim was billed by a different, unlisted entity, so the claim was processed out of network.", missed: "The member's directory check was real. The difference is who billed. That's the lead to verify." },
        knownVsUnknown(3, "Separates the known (OON processing, $380 to the deductible, $140 above allowed, the directory listing) from the unknown (whether the visit belonged to the in-network group, i.e. a billing error, or to a non-participating entity).", [fact("doc-eob"), fact("doc-directory")]),
        { id: "c-outcomes", category: "plan_knowledge", points: 3, basis: [rule("rhus.cost.in_network_no_cost_share"), rule("rhus.cost.deductible.out_of_network"), rule("rhus.cost.coinsurance.out_of_network"), rule("rhus.cost.balance_billing"), rule("rhus.cost.deductible.rules")], expectation: "Explains both outcomes with official rules. If in network: $0. If out of network: allowed amount to the $1,000 deductible, then 70%, plus possible balance billing. In- and out-of-network deductibles are tracked separately.", missed: "Lay out both branches with the plan rules so the member knows the range, without committing to one." },
      ],
      "Processed out of network: billed $520, allowed $380, all to the $1,000 out-of-network deductible, plan paid $0. The statement asks for $520, which is $380 member responsibility plus $140 above the allowed amount. The directory lists Dr. Shah in network with Heartline Cardiology Group (••4471), but the claim came from Heartline Cardiology Associates LLC (••9083), which isn't listed. Unknown: which entity the visit belonged to. Contact the practice and ask whether the claim should have been billed under the in-network group. If so, request a corrected claim for the administrator to reprocess. If it was in network, the member owes $0. If it was truly out of network, $380 to the deductible plus possible balance billing. Ask the practice to hold the bill while this is verified.",
    ),
    memberReply({
      accuracy: "Explains that the doctor is listed in network under one group but the bill came from a different company name, which is why it was treated as out of network. Says this is being verified, not concluded.",
      accuracyBasis: [fact("doc-directory"), fact("doc-claim")],
      promises: "Doesn't promise it will be reprocessed as in-network or that the member owes nothing. Can describe both possible outcomes.",
      next: "Asks the member to hold off paying while you check with the practice, and says when you'll update them.",
      empathy: "Validates that the member did check the directory and did the right thing.",
    }),
  ],
  debrief: {
    whatHappened:
      "Dr. Shah participates in the Cigna PPO network through Heartline Cardiology Group, but the visit was billed by Heartline Cardiology Associates LLC, an unlisted entity. The claim was processed out of network ($380 to the deductible), and the practice billed $520 including $140 above the allowed amount.",
    correctReasoning: [
      "Network status follows the billing entity. The directory listing and the claim's billing entity differ.",
      "Out of network: $380 allowed went to the $1,000 deductible, and $140 is above the allowed amount (balance billing).",
      "In network it would be $0 (official rules: specialist visit 100%, no deductible or copay).",
      "The answer isn't known yet. Verify with the practice, and if it was billed under the wrong entity, a corrected claim lets the administrator reprocess.",
      "R00.2 = why (palpitations). 99204 = what (new-patient visit).",
    ],
    modelMemberResponse:
      "Hi Sam, you did check, and you're right that Dr. Shah is listed as in-network. Here's the wrinkle: she's listed with Heartline Cardiology Group, but this bill came from a differently named company, Heartline Cardiology Associates, which isn't listed. That's why the plan treated the visit as out-of-network. It may be a billing mix-up on their end. I'm contacting the practice today to check which company should have billed, and if it was the wrong one, to have them resubmit. Please hold off on paying the $520 for now. I can't promise the result yet, but I'll update you by Monday.",
    conceptsToReview: ["network", "balance-billing", "claim-correction"],
  },
};

// =============================================================================
// CASE 08 · Intermediate · Diagnosis keying error → corrected claim
// =============================================================================
export const case08: SimulationCaseInput = {
  id: "case-08-wrong-diagnosis",
  version: 1,
  portfolioNumber: 8,
  code: "CASE-08",
  title: "Back pain therapy denied for an ear infection",
  summary: "A physical therapy evaluation was denied because the claim carries an ear-infection diagnosis. The referral says low back pain.",
  scenario: "CPT/ICD mismatch. A diagnosis keying error caused the denial, so the fix is a corrected claim, not an appeal. The EOB shows $0; the clinic bills $195.",
  recordingPriority: "medium",
  difficulty: "intermediate",
  status: "ready",
  isSample: false,
  caseTypes: ["coding", "denial", "claims_investigation"],
  skills: ["cpt", "icd10", "denials", "claim_correction", "appeals", "inconsistency_detection", "plain_english"],
  knowledge: knowledge(
    ["rhus.benefit.physical_therapy", "rhus.cost.in_network_no_cost_share", "rhus.structure.medical_necessity"],
    ["cpt", "icd10", "coding-error", "medical-necessity", "denial", "claim-correction", "appeal", "provider-statement", "eob", "member-responsibility"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-05-12T15:58:00Z",
    memberMessage: "My physical therapy claim got DENIED. Does my plan not cover PT for back pain?? The clinic wants $195 and I have 5 more visits scheduled.",
  },
  member: { name: "Lena Fischer", memberId: "RHU-61204-01", details: "Employee" },
  plan: RHUS_PLAN,
  provider: { name: "CoreMotion Physical Therapy", type: "Outpatient physical therapy clinic (fictional)", networkStatus: "in_network" },
  codes: [cpt("97162", "Physical therapy evaluation, moderate complexity."), icd("M54.50", "Low back pain, unspecified."), icd("H66.91", "Otitis media (middle-ear infection), unspecified, right ear.")],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION],
  documents: [
    { id: "doc-referral", type: "note", title: "Referral", provenance: caseFact(), author: "Dr. Owen Price (Family medicine)", date: "2026-04-02", body: "Refer to physical therapy: evaluate and treat. Diagnosis: low back pain (M54.50), 6 weeks' duration." },
    {
      id: "doc-claim",
      type: "claim",
      title: "Claim record",
      provenance: caseFact(),
      claimNumber: "CLM-26-0416-2087",
      status: "denied",
      receivedDate: "2026-04-16",
      processedDate: "2026-04-29",
      billingProvider: "CoreMotion Physical Therapy",
      networkStatus: "in_network",
      lines: [{ dateOfService: "2026-04-14", code: "97162", diagnosisCodes: ["H66.91"], units: 1, charge: 19500, lineStatus: "Denied", denialReason: "D17: Diagnosis is inconsistent with the procedure billed" }],
    },
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-0416-2087",
      processedDate: "2026-04-29",
      patient: "Lena Fischer",
      provider: "CoreMotion Physical Therapy",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-04-14", service: "PT evaluation", code: "97162", benefitKey: "physical_therapy", billed: 19500, remarkCodes: ["D17"] })],
      remarks: [{ code: "D17", text: "The diagnosis is inconsistent with the procedure billed. The provider may submit a corrected claim. Member responsibility: $0.00." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "CoreMotion Physical Therapy",
      statementDate: "2026-05-08",
      accountNumber: "CMPT-5512",
      lines: [{ dateOfService: "2026-04-14", description: "PT evaluation, moderate", code: "97162", charge: 19500 }],
      insurancePayments: 0,
      adjustments: 0,
      balanceDue: 19500,
      message: "Your insurance denied this claim. Please remit payment.",
    },
    planRulesDoc([
      ["Physical therapy", "rhus.benefit.physical_therapy"],
      ["In-network cost sharing", "rhus.cost.in_network_no_cost_share"],
      ["Medical necessity", "rhus.structure.medical_necessity"],
    ]),
  ],
  tasks: [
    choice("t-proc", "Which code on the claim describes the service performed?", [["97162", "97162"], ["h6691", "H66.91"], ["d17", "D17"], ["m5450", "M54.50"]], ["97162"], { category: "coding_understanding", points: 3, basis: [concept("cpt"), fact("doc-claim")], expectation: "Identifies the CPT code.", missed: "97162 (PT evaluation) is the CPT code: what was done." }, "97162."),
    choice("t-dx-claim", "Which diagnosis is on the claim?", [["h6691", "H66.91: ear infection"], ["m5450", "M54.50: low back pain"], ["none", "No diagnosis"], ["97162", "97162"]], ["h6691"], { category: "coding_understanding", points: 3, basis: [fact("doc-claim"), concept("icd10")], expectation: "Reads the diagnosis actually billed.", missed: "The claim carries H66.91 (otitis media, right ear). M54.50 appears only on the referral." }, "H66.91."),
    choice("t-mismatch", "Does the claim's diagnosis provide context for this procedure?", [["no", "No: an ear infection doesn't explain a physical therapy evaluation. The referral shows low back pain, so this looks like a keying error."], ["yes", "Yes: any diagnosis supports PT"], ["pt-not-covered", "It doesn't matter: PT isn't covered"], ["cannot", "Diagnosis and procedure can't be compared"]], ["no"], { category: "coding_understanding", points: 4, basis: [concept("medical-necessity"), concept("coding-error"), fact("doc-referral"), fact("doc-claim")], expectation: "Recognizes the diagnosis/procedure mismatch and its likely cause.", missed: "The ICD-10 (why) should plausibly support the CPT (what). The referral's M54.50 does; the billed H66.91 doesn't." }, "No. It's a likely keying error."),
    choice("t-path", "What's the right path to fix this?", [["corrected", "The clinic submits a corrected claim with the correct diagnosis"], ["appeal", "The member files an appeal"], ["pay", "The member pays and seeks reimbursement"], ["referral", "Get a new referral"]], ["corrected"], { category: "claims_reasoning", points: 4, basis: [concept("claim-correction"), concept("appeal"), fact("doc-eob")], expectation: "Chooses a correction over an appeal.", missed: "Errors in a claim are fixed by a corrected claim. An appeal disputes a decision that was right given the information submitted. The EOB itself invites a corrected claim." }, "A corrected claim from the provider."),
    amount("t-owed", "According to the EOB, what does the member owe right now?", 0, { category: "eob_interpretation", points: 4, basis: [fact("doc-eob")], expectation: "Reads $0.00.", missed: "The EOB's member responsibility is $0.00. The denial didn't shift the charge to the member." }, "$0.00", { measures: "eob_member_responsibility" }),
    choice("t-benefit", "What do the official rules say about in-network physical therapy?", [["covered", "Covered at 100% in network. The source states no pre-authorization requirement."], ["excluded", "Not covered for back pain"], ["pa", "Requires pre-authorization"], ["limit", "Limited to 20 visits"]], ["covered"], { category: "plan_knowledge", points: 3, basis: [rule("rhus.benefit.physical_therapy"), rule("rhus.cost.in_network_no_cost_share")], expectation: "States the benefit accurately.", missed: "Official rule: PT is 100% in network, including virtual visits. The source states no pre-authorization requirement and no visit limit. The denial was about coding, not coverage." }, "Covered at 100% in network."),
    choice("t-bill", "What should happen with the $195 statement?", [["hold", "It isn't supported by the EOB: ask the clinic to hold it and submit a corrected claim"], ["pay", "The member should pay it"], ["split", "The member should pay half"], ["ignore", "Ignore it; it will disappear"]], ["hold"], { category: "eob_interpretation", points: 3, basis: [fact("doc-bill"), fact("doc-eob"), concept("provider-statement")], expectation: "Ties the statement back to the EOB and the fix.", missed: "The statement conflicts with the EOB's $0. Coordinate a hold and a corrected claim. Don't tell the member to pay, and don't tell them to ignore it." }, "Hold it and correct the claim."),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-root", category: "claims_reasoning", points: 4, basis: [fact("doc-referral"), fact("doc-claim"), concept("coding-error")], expectation: "Identifies the root cause: the claim carries H66.91 instead of the referral's M54.50, most likely a keying error, so it was denied as diagnosis/procedure inconsistent.", missed: "Compare the referral with the claim. The diagnosis on the claim doesn't fit the service or the referral." },
        { id: "c-correction", category: "problem_solving", points: 3, basis: [concept("claim-correction"), concept("appeal")], expectation: "Recommends a corrected claim from CoreMotion, not an appeal, and explains why.", missed: "A correction fixes an error. An appeal argues with a decision. Using the wrong tool slows everything down." },
        { id: "c-coord", category: "problem_solving", points: 2, basis: [concept("care-coordination"), fact("doc-bill")], expectation: "Asks the clinic to hold the bill until the corrected claim is processed, then checks for the new EOB.", missed: "Protect the member while the fix happens, and close the loop when the new EOB arrives." },
      ],
      "CoreMotion billed 97162 (PT evaluation) with H66.91 (ear infection), while the referral says low back pain (M54.50). The claim was denied as diagnosis inconsistent with the procedure (D17). The EOB shows $0 and invites a corrected claim. This is most likely a keying error, so the fix is a corrected claim, not an appeal. PT is covered at 100% in network under the plan, with no pre-authorization stated. Ask CoreMotion to hold the $195 and resubmit with M54.50, then watch for the new EOB.",
    ),
    memberReply({
      accuracy: "Explains that PT is covered and the denial came from a wrong diagnosis code on the clinic's claim (a code for an ear infection), not from a coverage problem. The plan's statement shows $0 owed.",
      accuracyBasis: [fact("doc-claim"), fact("doc-eob"), rule("rhus.benefit.physical_therapy")],
      promises: "Doesn't promise the corrected claim will pay. Says it should be reviewed again once corrected.",
      next: "Asks the member not to pay the $195 for now, and says you'll contact the clinic and update them.",
    }),
  ],
  debrief: {
    whatHappened:
      "CoreMotion's claim listed an ear-infection diagnosis (H66.91) instead of the referral's low back pain (M54.50). The plan denied it as diagnosis/procedure inconsistent, with $0 member responsibility, and the clinic billed the member $195.",
    correctReasoning: [
      "CPT 97162 = what (PT evaluation). ICD-10 = why. H66.91 doesn't support PT; M54.50 does.",
      "The referral shows the intended diagnosis, so this is most likely a keying error.",
      "Errors are fixed by a corrected claim. Appeals are for disputing correct decisions.",
      "The EOB shows $0, so the statement isn't supported.",
      "Official rule: PT is 100% in network. The denial was about coding, not coverage.",
    ],
    modelMemberResponse:
      "Hi Lena, don't worry, your plan does cover physical therapy. The denial happened because the clinic's claim listed the wrong diagnosis code. It says ear infection instead of back pain, which looks like a typo. Your plan's statement shows you owe $0 right now, so please don't pay the $195. I'm contacting CoreMotion today to ask them to fix the code, resubmit the claim, and hold the bill meanwhile. Once the corrected claim is processed I'll check the result and let you know, at the latest by next Friday.",
    conceptsToReview: ["coding-error", "claim-correction", "medical-necessity"],
  },
};
