import type { SimulationCaseInput } from "@/domain/case";
import { caseFact } from "@/domain/provenance";
import {
  DOCS_ASSUMPTION, FICTION_ASSUMPTION, INVESTIGATION_PROMPT, RHUS_PLAN, amount, assumed, choice, concept, cpt, eobLine, fact, icd,
  investigation, knowledge, knownVsUnknown, memberReply, planRulesDoc, rule, selectAll,
} from "./helpers";

// =============================================================================
// CASE 05 · Intermediate · Pre-authorization never requested (penalty)
// =============================================================================
export const case05: SimulationCaseInput = {
  id: "case-05-pa-never-requested",
  version: 1,
  portfolioNumber: 5,
  code: "CASE-05",
  title: "\"Why am I paying for their mistake?\": the missing pre-authorization",
  summary: "Knee arthroscopy at an in-network surgery center. No pre-authorization was ever requested, and the plan applied the 10% penalty.",
  scenario: "Pre-authorization required but never requested. The official 10% penalty ($420) is applied, the bill matches the EOB, and the penalty doesn't count toward the out-of-pocket limit.",
  recordingPriority: "high",
  difficulty: "intermediate",
  status: "ready",
  isSample: false,
  caseTypes: ["prior_authorization", "medical_billing", "coding"],
  skills: ["prior_auth", "member_responsibility", "billing_reconciliation", "cpt", "icd10", "member_communication"],
  knowledge: knowledge(
    ["rhus.benefit.day_surgery", "rhus.pa.list.j", "rhus.pa.penalty", "rhus.pa.penalty_not_counted", "rhus.pa.member_must_confirm", "rhus.pa.provider_usually_requests", "rhus.cost.in_network_no_cost_share"],
    ["prior-authorization", "member-responsibility", "out-of-pocket-max", "provider-statement", "eob", "cpt", "icd10"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-09-29T20:14:00Z",
    memberMessage:
      "I had knee surgery last month at Lakeshore and now I have a $420 bill. The EOB says something about \"pre-authorization not obtained\". My surgeon's office told me they would take care of everything with insurance! Why am I paying for their mistake? And does this at least count toward my out-of-pocket max?",
  },
  member: { name: "Grace Liu", memberId: "RHU-40122-01", details: "Employee" },
  plan: RHUS_PLAN,
  provider: { name: "Lakeshore Surgery Center", type: "Ambulatory surgery center (fictional)", networkStatus: "in_network" },
  codes: [
    cpt("29881", "Knee arthroscopy (keyhole surgery) with removal or trimming of a torn meniscus, one compartment."),
    icd("S83.241A", "Other tear of medial meniscus, current injury, right knee, initial encounter."),
  ],
  assumptions: [
    FICTION_ASSUMPTION,
    DOCS_ASSUMPTION,
    "The EOB shows the pre-authorization reduction as a 'not covered' amount. That presentation is simulated: the source states the rule, not the EOB format.",
  ],
  documents: [
    {
      id: "doc-auth",
      type: "authorization",
      title: "Authorization lookup",
      provenance: caseFact(),
      status: "not_found",
      service: "Knee arthroscopy with meniscectomy",
      codes: ["29881"],
      diagnosisCodes: ["S83.241A"],
      requestingProvider: "No request on file",
      servicingProvider: "Lakeshore Surgery Center",
      notes: "No pre-authorization request found for this member and service between 07/01/2026 and 08/31/2026.",
      requirement: { benefitKey: "day_surgery", required: true },
    },
    {
      id: "doc-claim",
      type: "claim",
      title: "Claim record (facility)",
      provenance: caseFact(),
      claimNumber: "CLM-26-0824-7713",
      status: "processed_paid",
      receivedDate: "2026-08-24",
      processedDate: "2026-09-10",
      billingProvider: "Lakeshore Surgery Center",
      networkStatus: "in_network",
      lines: [{ dateOfService: "2026-08-20", code: "29881", diagnosisCodes: ["S83.241A"], units: 1, charge: 980000, lineStatus: "Paid with reduction (PA02)" }],
    },
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-0824-7713",
      processedDate: "2026-09-10",
      patient: "Grace Liu",
      provider: "Lakeshore Surgery Center",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-08-20", service: "Knee arthroscopy", code: "29881", benefitKey: "day_surgery", billed: 980000, allowed: 420000, planPaid: 378000, notCovered: 42000, memberResponsibility: 42000, remarkCodes: ["PA02"] })],
      remarks: [{ code: "PA02", text: "Pre-authorization not obtained. Covered charges reduced by 10% (maximum $500). This amount does not count toward the deductible or out-of-pocket maximum." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Lakeshore Surgery Center",
      statementDate: "2026-09-22",
      accountNumber: "LSC-301877",
      lines: [{ dateOfService: "2026-08-20", description: "Arthroscopy, knee, meniscectomy", code: "29881", charge: 980000 }],
      insurancePayments: 378000,
      adjustments: 560000,
      balanceDue: 42000,
      dueDate: "2026-10-22",
    },
    planRulesDoc([
      ["Day surgery", "rhus.benefit.day_surgery"],
      ["Pre-authorization list", "rhus.pa.list.j"],
      ["Who requests pre-authorization", "rhus.pa.provider_usually_requests"],
      ["Member's responsibility", "rhus.pa.member_must_confirm"],
      ["Missing pre-authorization", "rhus.pa.penalty"],
      ["Penalty and accumulators", "rhus.pa.penalty_not_counted"],
    ]),
  ],
  tasks: [
    choice("t-pa-required", "Did this outpatient knee surgery require pre-authorization?", [["yes", "Yes: day surgery is marked pre-authorization required, and outpatient surgery is on the official list (J)"], ["no", "No: only imaging needs pre-authorization"], ["in-only", "Only for out-of-network surgery centers"], ["inpatient", "Only if the member stays overnight"]], ["yes"], { category: "prior_authorization", points: 3, basis: [rule("rhus.benefit.day_surgery"), rule("rhus.pa.list.j")], expectation: "Knows outpatient surgery requires pre-authorization.", missed: "Official rules: the day-surgery benefit is marked 'Pre-authorization required', and list item J covers outpatient surgery and procedures." }, "Yes."),
    choice("t-pa-status", "What does the authorization lookup show?", [["none", "No request was ever found for this service"], ["unlinked", "An approved authorization exists but wasn't linked"], ["denied", "A request was made and denied"], ["expired", "An authorization existed but had expired"]], ["none"], { category: "prior_authorization", points: 3, basis: [fact("doc-auth")], expectation: "Reads 'not found' correctly. This is the 'required but missing' scenario.", missed: "Separate the four questions. Required: yes. Requested: no request on file. That is different from an unlinked or expired authorization." }, "No request on file."),
    amount("t-penalty", "Using the official rule, calculate the reduction on this claim (covered charges = $4,200 allowed).", 42000, { category: "plan_knowledge", points: 4, basis: [rule("rhus.pa.penalty"), fact("doc-eob")], expectation: "Calculates 10% of $4,200 = $420 (under the $500 cap).", missed: "Official rule: covered charges are reduced by 10%, up to $500. 10% × $4,200 = $420, which is under the $500 cap. The base is the covered (allowed) amount, not the $9,800 billed amount." }, "$420.00"),
    choice("t-cap", "If the same thing happened on a claim with $7,000 of covered charges, what would the pre-authorization reduction be?", [["500", "$500"], ["700", "$700"], ["70", "$70"], ["0", "$0"]], ["500"], { category: "plan_knowledge", points: 3, basis: [rule("rhus.pa.penalty")], expectation: "Applies the $500 cap.", missed: "10% of $7,000 is $700, but the official rule caps the reduction at $500." }, "$500 (the cap)."),
    choice("t-oop", "Does the $420 count toward the member's out-of-pocket limit?", [["no", "No: the pre-authorization penalty doesn't count toward the deductible or out-of-pocket maximum"], ["yes", "Yes: everything the member pays counts"], ["ded", "It counts toward the deductible only"], ["depends", "Only if the member appeals"]], ["no"], { category: "plan_knowledge", points: 3, basis: [rule("rhus.pa.penalty_not_counted")], expectation: "Knows the penalty doesn't accumulate.", missed: "Official rule: the penalty does not count toward the deductible or the out-of-pocket maximum." }, "No."),
    amount("t-owed", "According to the EOB, what is the member responsibility?", 42000, { category: "eob_interpretation", points: 3, basis: [fact("doc-eob")], expectation: "Reads $420.00.", missed: "The EOB shows $420.00 member responsibility: the plan paid $3,780 of the $4,200 allowed amount." }, "$420.00", { measures: "eob_member_responsibility" }),
    choice("t-bill-eob", "Does the surgery center's statement agree with the EOB?", [["yes", "Yes: both show $420 owed after the plan's payment and the contractual adjustment"], ["higher", "No: the statement is higher"], ["lower", "No: the statement is lower"], ["zero", "No: the EOB shows $0"]], ["yes"], { category: "eob_interpretation", points: 3, basis: [fact("doc-bill"), fact("doc-eob"), concept("provider-statement")], expectation: "Reconciles statement and EOB.", missed: "Charge $9,800 − insurance $3,780 − adjustment $5,600 = $420, exactly the EOB member responsibility. Not every bill is wrong." }, "Yes."),
    choice("t-codes", "Which pairing is correct?", [["right", "29881 = the procedure (knee scope); S83.241A = the diagnosis (meniscus tear)"], ["reversed", "29881 = the diagnosis; S83.241A = the procedure"], ["both-proc", "Both are procedure codes"], ["both-dx", "Both are diagnosis codes"]], ["right"], { category: "coding_understanding", points: 4, basis: [concept("cpt"), concept("icd10")], expectation: "Pairs CPT with what and ICD-10 with why.", missed: "CPT 29881 describes what was done (arthroscopic meniscectomy). ICD-10 S83.241A describes why (medial meniscus tear, right knee)." }, "29881 = procedure, S83.241A = diagnosis."),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-correct", category: "claims_reasoning", points: 4, basis: [fact("doc-auth"), fact("doc-eob"), rule("rhus.pa.penalty"), assumed(2)], expectation: "Concludes the claim appears processed according to the official rule: pre-authorization was required, no request was found, a 10% reduction ($420) was applied, and the statement matches the EOB.", missed: "Here the plan's documents are internally consistent. The member does owe $420 per the EOB, unless verification turns up a request." },
        { id: "c-responsibility", category: "prior_authorization", points: 3, basis: [rule("rhus.pa.member_must_confirm"), rule("rhus.pa.provider_usually_requests")], expectation: "Explains, without blaming, that the provider usually requests pre-authorization but the plan makes the member responsible for confirming it. Notes the sources don't say whether a provider's failure changes who bears the penalty, so that can't be promised.", missed: "Official rules: the in-network provider usually requests pre-authorization, and the member is responsible for confirming it. Don't promise the penalty will move to the provider. The sources don't establish that." },
        knownVsUnknown(3, "Plans to verify whether the surgeon's office actually submitted a request (ask for a confirmation or reference number), and to ask the claims administrator whether anything changes if a request is found.", [fact("doc-auth"), concept("care-coordination")]),
      ],
      "Outpatient knee arthroscopy (29881, S83.241A) requires pre-authorization (day-surgery row; list item J). The lookup shows no request on file. The claim was paid with the official reduction: 10% of the $4,200 allowed amount = $420 (under the $500 cap). Lakeshore's statement matches the EOB ($9,800 − $3,780 − $5,600 = $420). The penalty doesn't count toward the deductible or out-of-pocket maximum. Unknown: whether the surgeon's office submitted anything. Ask them for proof of a request, and if they have one, raise it with the claims administrator. Don't promise the $420 will be removed.",
    ),
    memberReply({
      accuracy: "Explains accurately that the plan applied its rule for missing pre-approval (10% of the covered amount, here $420), that the bill matches the plan's statement, and that the amount doesn't count toward the out-of-pocket maximum.",
      accuracyBasis: [fact("doc-eob"), rule("rhus.pa.penalty"), rule("rhus.pa.penalty_not_counted")],
      promises: "Doesn't promise the $420 will be waived or charged to the surgeon's office. Doesn't state as fact that the office made a mistake before verifying.",
      next: "Says you'll ask the surgeon's office whether they submitted a request and follow up by a set day. Suggests holding payment until then, and a tip to confirm approval before future procedures.",
      empathy: "Acknowledges the frustration of being told 'we'll handle it' and still getting a bill.",
    }),
  ],
  debrief: {
    whatHappened:
      "Outpatient knee surgery required pre-authorization, but no request was ever submitted. The plan paid the claim with its documented reduction: 10% of the $4,200 covered charges = $420. The surgery center's statement matches the EOB.",
    correctReasoning: [
      "Official rules: day surgery and outpatient surgery (list J) require pre-authorization.",
      "The lookup shows required but never requested. That's different from 'approved but unlinked' or 'expired'.",
      "Official rule: covered charges are reduced by 10%, up to $500. $4,200 × 10% = $420.",
      "Official rule: the penalty doesn't count toward the deductible or the out-of-pocket maximum.",
      "Statement and EOB agree, so the investigation question is 'was a request made?', not 'is the bill wrong?'.",
      "Official rules: the provider usually requests pre-authorization, but the member must confirm it. The sources don't say the penalty shifts to the provider, so don't promise that.",
    ],
    modelMemberResponse:
      "Hi Grace, I completely understand the frustration. You were told it would be handled, and now there's a bill. Here's what I found: knee surgery like yours needs pre-approval from the plan, and there's no record of a request being sent. When that happens, your plan reduces what it pays by 10%, which on this claim is $420. The surgery center's bill matches what your plan's statement shows. Unfortunately, that amount doesn't count toward your out-of-pocket maximum. I'm asking your surgeon's office today whether they submitted a request and have a reference number. If they did, I'll take it to the claims team. I can't promise it changes the outcome, but it's worth checking. You may want to hold off paying until I update you on Friday.",
    conceptsToReview: ["prior-authorization", "out-of-pocket-max", "member-responsibility"],
  },
};

// =============================================================================
// CASE 06 · Intermediate · Authorization covers a different service (CT vs MRI)
// =============================================================================
export const case06: SimulationCaseInput = {
  id: "case-06-ct-approved-mri-billed",
  version: 1,
  portfolioNumber: 6,
  code: "CASE-06",
  title: "Approved for a CT, billed for an MRI",
  summary: "The member was told their scan was approved, but the approval was for a CT and an MRI was performed. The claim is denied and the imaging center bills $2,850.",
  scenario: "The authorization covers a different service. The order changed from CT to MRI the day before, and nobody requested a new approval. The EOB shows $0; the bill shows $2,850.",
  recordingPriority: "high",
  difficulty: "intermediate",
  status: "ready",
  isSample: false,
  caseTypes: ["prior_authorization", "denial", "coding", "medical_billing"],
  skills: ["prior_auth", "cpt", "inconsistency_detection", "denials", "billing_reconciliation", "provider_communication"],
  knowledge: knowledge(
    ["rhus.benefit.diagnostic_mri", "rhus.benefit.diagnostic_ct", "rhus.pa.list.k", "rhus.pa.penalty", "rhus.pa.provider_usually_requests", "rhus.structure.bywater_tpa"],
    ["prior-authorization", "authorization-linking", "cpt", "icd10", "denial", "claim-correction", "provider-statement", "eob", "member-responsibility"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-06-24T11:47:00Z",
    memberMessage:
      "My MRI got denied?? I specifically asked my doctor's office if my scan was approved and they said YES. Now Northgate Imaging says I owe $2,850. What happened?",
  },
  member: { name: "Aisha Rahman", memberId: "RHU-38810-01", details: "Employee" },
  plan: RHUS_PLAN,
  provider: { name: "Northgate Imaging", type: "Outpatient imaging center (fictional)", networkStatus: "in_network" },
  codes: [
    cpt("70450", "CT scan of the head/brain without contrast."),
    cpt("70551", "MRI of the brain without contrast."),
    icd("R51.9", "Headache, unspecified."),
  ],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION],
  documents: [
    {
      id: "doc-auth",
      type: "authorization",
      title: "Authorization record",
      provenance: caseFact(),
      authNumber: "AUTH-2026-051144",
      status: "approved",
      service: "CT head without contrast",
      codes: ["70450"],
      diagnosisCodes: ["R51.9"],
      requestingProvider: "Dr. Jonah Feld (Neurology)",
      servicingProvider: "Northgate Imaging",
      requestedDate: "2026-05-08",
      decisionDate: "2026-05-10",
      validFrom: "2026-05-10",
      validTo: "2026-07-09",
      notes: "Approved for CT. No other authorization requests on file for this member.",
      requirement: { benefitKey: "diagnostic_ct", required: true },
    },
    { id: "doc-report", type: "note", title: "Imaging report (header)", provenance: caseFact(), author: "Northgate Imaging", date: "2026-05-19", body: "Exam performed: MRI brain without contrast. Clinical indication: chronic headache. Note: order changed from CT head to MRI brain on 05/18 by Dr. Feld per radiologist recommendation." },
    {
      id: "doc-claim",
      type: "claim",
      title: "Claim record",
      provenance: caseFact(),
      claimNumber: "CLM-26-0521-0928",
      status: "denied",
      receivedDate: "2026-05-21",
      processedDate: "2026-06-04",
      billingProvider: "Northgate Imaging",
      networkStatus: "in_network",
      authorizationNumberOnClaim: "AUTH-2026-051144",
      lines: [{ dateOfService: "2026-05-19", code: "70551", diagnosisCodes: ["R51.9"], units: 1, charge: 285000, lineStatus: "Denied", denialReason: "AM01: Service billed does not match the authorization on file" }],
    },
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-0521-0928",
      processedDate: "2026-06-04",
      patient: "Aisha Rahman",
      provider: "Northgate Imaging",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-05-19", service: "MRI brain", code: "70551", benefitKey: "diagnostic_mri", billed: 285000, remarkCodes: ["AM01"] })],
      remarks: [{ code: "AM01", text: "The service billed does not match the authorization on file. Provider: submit an authorization or corrected claim for the service performed. Member responsibility for this line: $0.00." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Northgate Imaging",
      statementDate: "2026-06-18",
      accountNumber: "NGI-77120",
      lines: [{ dateOfService: "2026-05-19", description: "MRI brain w/o contrast", code: "70551", charge: 285000 }],
      insurancePayments: 0,
      adjustments: 0,
      balanceDue: 285000,
      message: "Insurance denied. Balance is patient responsibility.",
    },
    planRulesDoc([
      ["MRI benefit", "rhus.benefit.diagnostic_mri"],
      ["CT benefit", "rhus.benefit.diagnostic_ct"],
      ["Pre-authorization list", "rhus.pa.list.k"],
      ["Who requests pre-authorization", "rhus.pa.provider_usually_requests"],
      ["Missing pre-authorization", "rhus.pa.penalty"],
    ]),
  ],
  tasks: [
    choice("t-performed", "Which service was actually performed?", [["mri", "MRI brain (70551): the claim and the imaging report agree"], ["ct", "CT head (70450), as authorized"], ["both", "Both a CT and an MRI"], ["unknown", "Can't be determined"]], ["mri"], { category: "claims_reasoning", points: 3, basis: [fact("doc-claim"), fact("doc-report")], expectation: "Uses the report and the claim to establish what was done.", missed: "The claim bills 70551 and the imaging report confirms an MRI. The order changed on 05/18." }, "MRI brain (70551)."),
    choice("t-auth-covers", "What does the authorization cover?", [["ct", "A CT of the head (70450) only"], ["mri", "An MRI of the brain"], ["any", "Any imaging for headache"], ["any-dx", "Any service billed with R51.9"]], ["ct"], { category: "prior_authorization", points: 4, basis: [fact("doc-auth"), concept("authorization-linking")], expectation: "Reads the authorized service and code.", missed: "Authorizations are specific: AUTH-2026-051144 covers 70450 (CT head), not 70551. Same diagnosis doesn't mean same service." }, "CT head only."),
    choice("t-mri-needs-pa", "Under the plan, did the MRI need its own pre-authorization?", [["yes", "Yes: MRI and CT are both on list K, and an approval for one doesn't cover the other"], ["no-same-dx", "No: the CT approval covers any scan for the same diagnosis"], ["no-mri", "No: MRI doesn't need pre-authorization"], ["oon", "Only if Northgate were out of network"]], ["yes"], { category: "prior_authorization", points: 4, basis: [rule("rhus.pa.list.k"), rule("rhus.benefit.diagnostic_mri"), concept("authorization-linking")], expectation: "Knows MRI requires its own approval.", missed: "Official rule: MRI, PET and CT are all on list item K. A changed order needs its own approval." }, "Yes."),
    amount("t-owed", "According to the EOB, what is the member responsibility right now?", 0, { category: "eob_interpretation", points: 4, basis: [fact("doc-eob")], expectation: "Reads $0.00.", missed: "The EOB shows $0.00 member responsibility and asks the provider to act. The $2,850 comes only from the provider's statement." }, "$0.00", { measures: "eob_member_responsibility" }),
    choice("t-bill-eob", "How does Northgate's statement compare with the EOB?", [["mismatch", "It asks for $2,850 while the EOB shows $0 and says the provider must submit an authorization or corrected claim"], ["match", "It matches the EOB"], ["eob-wrong", "The EOB is wrong because the claim was denied"], ["lower", "It asks for less than the EOB"]], ["mismatch"], { category: "eob_interpretation", points: 4, basis: [fact("doc-bill"), fact("doc-eob"), concept("provider-statement")], expectation: "Identifies that the bill isn't supported by the EOB.", missed: "A denial doesn't automatically make the charge the member's. This EOB assigns $0 to the member and puts the action on the provider." }, "The statement isn't supported by the EOB."),
    selectAll(
      "t-codes",
      "Select every statement that is true.",
      [["proc", "70551 is the procedure on the claim"], ["dx", "R51.9 explains why imaging was done"], ["diff", "The authorized code (70450) differs from the billed code (70551)"], ["r51-proc", "R51.9 is the procedure code"], ["dx-wrong", "The diagnosis must be wrong because the claim was denied"]],
      ["proc", "dx", "diff"],
      { category: "coding_understanding", points: 5, basis: [concept("cpt"), concept("icd10"), fact("doc-claim"), fact("doc-auth")], expectation: "Correctly separates CPT (what) from ICD-10 (why) and spots the CPT mismatch.", missed: "The mismatch is in the CPT (what was done), not the diagnosis (why). R51.9 supports both a CT and an MRI for headache." },
      "70551 is the procedure, R51.9 is the reason, and the CPT on the authorization differs from the claim.",
    ),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-cause", category: "claims_reasoning", points: 5, basis: [fact("doc-report"), fact("doc-auth"), fact("doc-claim")], expectation: "Identifies the root cause: the order changed from CT to MRI the day before, the CT authorization doesn't cover the MRI, and the claim was denied for the mismatch. The member didn't cause it.", missed: "The member's 'it was approved' was true, but for a different service. Find the change (imaging report) and explain it." },
        knownVsUnknown(3, "Separates the known (MRI performed; only a CT authorized; denial; EOB $0) from the unknown (whether anyone requested MRI approval; how the claim will finally be resolved).", [fact("doc-auth"), fact("doc-eob")]),
        { id: "c-contacts", category: "problem_solving", points: 3, basis: [rule("rhus.structure.bywater_tpa"), rule("rhus.pa.provider_usually_requests"), concept("care-coordination"), concept("claim-correction")], expectation: "Contacts: Dr. Feld's office and Northgate about the authorization for the service actually performed (or a corrected submission); the claims administrator (Bywater) about next steps; and Northgate to hold the bill.", missed: "The provider side must fix the authorization/claim mismatch. The administrator decides the claim. Northgate must stop billing the member meanwhile." },
        { id: "c-exposure", category: "plan_knowledge", points: 2, basis: [rule("rhus.pa.penalty")], expectation: "Notes that if MRI pre-authorization was truly never obtained, the plan's documented consequence is a 10% reduction of covered charges (up to $500), not the full $2,850 charge, and that the final outcome must be confirmed.", missed: "Official rule: missing pre-authorization reduces covered charges by 10%, up to $500. Don't tell the member they owe $2,850, and don't promise $0 either." },
      ],
      "Dr. Feld got AUTH-2026-051144 for a CT head (70450). On 05/18 the order changed to an MRI brain (70551), which was performed on 05/19, but no approval for the MRI is on file. Northgate billed 70551 with the CT authorization number, and the claim was denied (AM01) as not matching the authorization. The EOB shows $0 member responsibility and puts the action on the provider. Northgate's $2,850 statement isn't supported. Unknown: whether an MRI request was made, and the final outcome. Contact Dr. Feld's office and Northgate about the MRI authorization or a corrected submission, ask Northgate to hold the bill, and follow up with the administrator. Under the official rule, a genuinely missing pre-authorization reduces covered charges by 10% (up to $500), so even the worst case isn't $2,850.",
    ),
    memberReply({
      accuracy: "Explains that the approval was for a CT but an MRI was done after the order changed, so the claim didn't match the approval. The plan's statement shows the member owes $0 right now.",
      accuracyBasis: [fact("doc-auth"), fact("doc-report"), fact("doc-eob")],
      promises: "Doesn't promise the MRI will be paid in full or that the member will owe nothing. Says it's being sorted out with the provider.",
      next: "Asks the member not to pay the $2,850 while you work with the doctor's office and Northgate, and says when you'll update them.",
      empathy: "Acknowledges that the member did the right thing by checking for approval first.",
    }),
  ],
  debrief: {
    whatHappened:
      "The approval was for a CT. The day before the scan, the order changed to an MRI on the radiologist's advice, and no one requested approval for the MRI. The claim was denied as not matching the authorization. The EOB shows $0 member responsibility, but Northgate billed the member $2,850.",
    correctReasoning: [
      "Authorizations are service-specific: 70450 (CT) is not 70551 (MRI).",
      "Official rule: MRI and CT are both on list K. A changed order needs its own approval.",
      "The EOB shows $0 and puts the action on the provider, so the statement isn't supported.",
      "The mismatch is in the CPT (what), not the ICD-10 (why). R51.9 fits either scan.",
      "Official rule: a genuinely missing pre-authorization means a 10% reduction (up to $500), so the worst case isn't $2,850. The final outcome still needs verification.",
      "The fix runs through the ordering provider and the imaging center (authorization or corrected submission), with the administrator deciding the claim.",
    ],
    modelMemberResponse:
      "Hi Aisha, you did the right thing by checking, and I'm sorry this happened. Here's what I found: the approval your doctor's office got was for a CT scan. The day before your appointment, the order was changed to an MRI, and an approval for the MRI was never requested, so the claim didn't match. Your plan's statement shows you owe $0 at this point, so please don't pay the $2,850. I'm contacting Dr. Feld's office and Northgate today to sort out the approval for the scan you actually had, and asking Northgate to pause the bill. I can't promise the final outcome yet, but I'll keep you posted and update you by Tuesday.",
    conceptsToReview: ["authorization-linking", "cpt", "claim-correction"],
  },
};
