import type { SimulationCaseInput } from "@/domain/case";
import { caseFact } from "@/domain/provenance";
import {
  DOCS_ASSUMPTION, FICTION_ASSUMPTION, INVESTIGATION_PROMPT, RHUS_PLAN, amount, assumed, choice, concept, cpt, eobLine, fact, icd,
  investigation, knowledge, knownVsUnknown, memberReply, planRulesDoc, rule, selectAll,
} from "./helpers";

// =============================================================================
// CASE 11 · Intermediate+ · Corrected claim paid, stale bill (CPT in dx field)
// =============================================================================
export const case11: SimulationCaseInput = {
  id: "case-11-corrected-claim",
  version: 1,
  portfolioNumber: 11,
  code: "CASE-11",
  title: "Fixed claim, old bill",
  summary: "The original allergy-testing claim was denied because a CPT code was typed into the diagnosis field. The corrected claim was paid, but the clinic's statement still reflects the old denial.",
  scenario: "Two claims and two EOBs: the original was denied (CPT code in the diagnosis field) and the corrected claim paid. The statement, dated after the correction, still shows the denial. Teaches which document is current.",
  recordingPriority: "medium",
  difficulty: "intermediate_plus",
  status: "ready",
  isSample: false,
  caseTypes: ["claims_investigation", "coding", "medical_billing", "denial"],
  skills: ["claim_correction", "cpt", "icd10", "denials", "billing_reconciliation", "inconsistency_detection"],
  knowledge: knowledge(
    ["rhus.benefit.allergy_testing", "rhus.cost.in_network_no_cost_share"],
    ["claim-correction", "coding-error", "cpt", "icd10", "denial", "claim-statuses", "provider-statement", "eob", "allowed-amount"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-04-09T17:30:00Z",
    memberMessage:
      "Hi, Willow Allergy sent me a bill for $640 saying insurance denied my allergy testing. But I got another letter from the plan in March that looked different? I'm confused about which one is right.",
  },
  member: { name: "Hannah Brooks", memberId: "RHU-25587-03", details: "Dependent (child of employee), age 24" },
  plan: RHUS_PLAN,
  provider: { name: "Willow Allergy & Asthma", type: "Allergy clinic (fictional)", networkStatus: "in_network" },
  codes: [cpt("95004", "Allergy skin-prick tests, per test."), icd("J30.1", "Allergic rhinitis due to pollen.")],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION, "This is the member's first allergy testing under the plan."],
  documents: [
    {
      id: "doc-claim-original",
      type: "claim",
      title: "Claim record: CLM-26-0212-0731 (original)",
      provenance: caseFact(),
      deliberateErrors: ["The CPT code 95004 was entered in the diagnosis field; no ICD-10 code was submitted."],
      claimNumber: "CLM-26-0212-0731",
      status: "denied",
      receivedDate: "2026-02-12",
      processedDate: "2026-02-25",
      billingProvider: "Willow Allergy & Asthma",
      networkStatus: "in_network",
      lines: [{ dateOfService: "2026-02-10", code: "95004", diagnosisCodes: ["95004"], units: 40, charge: 64000, lineStatus: "Denied", denialReason: "DX1: Missing or invalid diagnosis code" }],
    },
    {
      id: "doc-eob-original",
      type: "eob",
      title: "Explanation of Benefits: CLM-26-0212-0731",
      provenance: caseFact(),
      claimNumber: "CLM-26-0212-0731",
      processedDate: "2026-02-25",
      patient: "Hannah Brooks",
      provider: "Willow Allergy & Asthma",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-02-10", service: "Allergy skin tests (40)", code: "95004", benefitKey: "allergy_testing", billed: 64000, remarkCodes: ["DX1"] })],
      remarks: [{ code: "DX1", text: "Missing or invalid diagnosis code. Provider may submit a corrected claim. Member responsibility: $0.00." }],
    },
    {
      id: "doc-claim-corrected",
      type: "claim",
      title: "Claim record: CLM-26-0320-5518 (corrected / replacement)",
      provenance: caseFact(),
      claimNumber: "CLM-26-0320-5518",
      status: "processed_paid",
      receivedDate: "2026-03-20",
      processedDate: "2026-03-31",
      billingProvider: "Willow Allergy & Asthma",
      networkStatus: "in_network",
      lines: [{ dateOfService: "2026-02-10", code: "95004", diagnosisCodes: ["J30.1"], units: 40, charge: 64000, lineStatus: "Paid. Replaces CLM-26-0212-0731" }],
    },
    {
      id: "doc-eob-corrected",
      type: "eob",
      title: "Explanation of Benefits: CLM-26-0320-5518",
      provenance: caseFact(),
      claimNumber: "CLM-26-0320-5518",
      processedDate: "2026-03-31",
      patient: "Hannah Brooks",
      provider: "Willow Allergy & Asthma",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-02-10", service: "Allergy skin tests (40)", code: "95004", benefitKey: "allergy_testing", billed: 64000, allowed: 30000, planPaid: 30000, remarkCodes: ["RP1"] })],
      remarks: [{ code: "RP1", text: "Corrected claim. Replaces claim CLM-26-0212-0731." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Willow Allergy & Asthma",
      statementDate: "2026-04-05",
      accountNumber: "WAA-31094",
      lines: [{ dateOfService: "2026-02-10", description: "Allergy testing, percutaneous x40", code: "95004", charge: 64000 }],
      insurancePayments: 0,
      adjustments: 0,
      balanceDue: 64000,
      message: "Insurance denied claim CLM-26-0212-0731. Please remit.",
    },
    planRulesDoc([
      ["Allergy testing", "rhus.benefit.allergy_testing"],
      ["In-network cost sharing", "rhus.cost.in_network_no_cost_share"],
    ]),
  ],
  tasks: [
    choice("t-error", "What was wrong with the original claim?", [["cpt-in-dx", "A CPT code (95004) was entered in the diagnosis field, so there was no valid ICD-10 diagnosis"], ["oon", "The clinic is out of network"], ["no-auth", "Allergy testing needed pre-authorization"], ["wrong-patient", "It was billed under the wrong patient"]], ["cpt-in-dx"], { category: "coding_understanding", points: 4, basis: [fact("doc-claim-original"), concept("coding-error"), concept("icd10")], expectation: "Spots the CPT code in the diagnosis field.", missed: "The original claim's diagnosis field contains '95004', a CPT procedure code. A claim needs an ICD-10 code to say why the service was done." }, "A CPT code was in the diagnosis field."),
    selectAll("t-dx", "Which of these are ICD-10 diagnosis codes?", [["j301", "J30.1"], ["95004", "95004"], ["rp1", "RP1"], ["dx1", "DX1"]], ["j301"], { category: "coding_understanding", points: 3, basis: [concept("icd10"), concept("cpt")], expectation: "Selects only the ICD-10 code.", missed: "J30.1 (allergic rhinitis due to pollen) is the diagnosis. 95004 is CPT (what was done). RP1 and DX1 are remark codes." }, "Only J30.1."),
    choice("t-latest", "Which EOB reflects the plan's current decision?", [["corrected", "The 03/31 EOB for the corrected claim (paid, $0 member responsibility)"], ["original", "The 02/25 EOB (denied)"], ["both", "Both apply, so the member owes for one of them"], ["neither", "Neither: the claim is still open"]], ["corrected"], { category: "claims_reasoning", points: 4, basis: [fact("doc-eob-corrected"), fact("doc-claim-corrected"), concept("claim-correction")], expectation: "Identifies the replacement claim as current.", missed: "A corrected (replacement) claim supersedes the original. RP1 says so explicitly. Always look for the latest EOB." }, "The corrected-claim EOB from 03/31."),
    amount("t-owed", "Across both EOBs, what is the member responsibility?", 0, { category: "eob_interpretation", points: 3, basis: [fact("doc-eob-original"), fact("doc-eob-corrected")], expectation: "Reads $0.00.", missed: "Both EOBs show $0.00 member responsibility. The corrected claim was paid in full." }, "$0.00", { measures: "eob_member_responsibility" }),
    amount("t-allowed", "What allowed amount did the plan apply on the corrected claim?", 30000, { category: "eob_interpretation", points: 3, basis: [fact("doc-eob-corrected"), concept("allowed-amount")], expectation: "Reads allowed $300.00.", missed: "Allowed $300.00, all paid by the plan. The $340 difference from the $640 charge is a network write-off." }, "$300.00"),
    choice("t-statement", "What's wrong with Willow's 04/05 statement?", [["stale", "It's dated after the corrected claim was paid but still reflects the old denial, with no payment or adjustment posted"], ["right", "Nothing: the original claim was denied"], ["oon", "It includes out-of-network balance billing"], ["deductible", "It applies the member's deductible"]], ["stale"], { category: "eob_interpretation", points: 4, basis: [fact("doc-bill"), fact("doc-eob-corrected"), concept("provider-statement")], expectation: "Identifies the stale statement.", missed: "Compare dates: the corrected claim was paid 03/31, and the statement on 04/05 still cites the original denial. Billing systems often lag behind corrections." }, "It's stale and reflects the superseded denial."),
    choice("t-limit", "What does the plan's allergy-testing rule say?", [["limit", "100% in network, limited to 1 testing (based on provider type)"], ["unlimited", "Unlimited at 100%"], ["pa", "Requires pre-authorization"], ["excluded", "Not covered"]], ["limit"], { category: "plan_knowledge", points: 3, basis: [rule("rhus.benefit.allergy_testing"), assumed(2)], expectation: "States the benefit and its limit accurately.", missed: "Official rule: allergy testing is 100% in network (70% after deductible out of network), limited to '1 testing (based on provider type)'. Worth mentioning for future testing, without inventing a time period." }, "100% in network, 1 testing."),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-timeline", category: "claims_reasoning", points: 4, basis: [fact("doc-claim-original"), fact("doc-claim-corrected"), fact("doc-bill")], expectation: "Reconstructs the timeline: the original was denied (CPT in the diagnosis field), the corrected claim with J30.1 was paid on 03/31, and the 04/05 statement still reflects the superseded denial.", missed: "Lay the documents out in date order. The 'conflicting' letters are just two stages of the same claim." },
        { id: "c-coord", category: "problem_solving", points: 4, basis: [concept("care-coordination"), fact("doc-eob-corrected")], expectation: "Contacts Willow's billing office with the corrected claim number and payment, and asks them to post the $300 payment and $340 adjustment and zero the balance. No appeal or further correction is needed.", missed: "The claim side is already fixed. What remains is a provider posting update." },
        knownVsUnknown(2, "Notes that the cause of the lag (unposted payment) is likely but should be confirmed with Willow, and that the allergy-testing limit's time period isn't stated in the source.", [fact("doc-bill"), rule("rhus.benefit.allergy_testing")]),
      ],
      "Original claim CLM-26-0212-0731 had '95004' (a CPT code) in the diagnosis field and was denied (DX1, $0 member). Willow sent a corrected claim with J30.1, which was paid on 03/31: allowed $300, plan paid $300, member $0. Willow's 04/05 statement still cites the original denial with no payment or adjustment posted, so it's stale. Contact Willow billing with CLM-26-0320-5518 so they post the payment and adjustment and zero the balance. Note for the future: the plan limits allergy testing to 1 testing (based on provider type).",
    ),
    memberReply({
      accuracy: "Explains that the first letter was a denial caused by a coding error on the clinic's side, that the clinic fixed it and the plan paid in full in March, and that the member owes $0.",
      accuracyBasis: [fact("doc-eob-corrected"), fact("doc-eob-original")],
      promises: "Doesn't promise when Willow will update its records. Says what you're doing.",
      next: "Asks the member not to pay the $640. Says you're sending Willow the payment details, and when you'll confirm.",
    }),
  ],
  debrief: {
    whatHappened:
      "Willow's first claim had a CPT code in the diagnosis field and was denied. Willow corrected it with the right diagnosis (J30.1), and the plan paid it in full on 03/31. Willow's 04/05 statement still reflects the original denial.",
    correctReasoning: [
      "A CPT code (what) can't stand in for an ICD-10 code (why), so the original was denied for a missing diagnosis.",
      "The corrected claim replaced the original. The latest EOB is the current decision.",
      "Both EOBs show $0 member responsibility. Allowed $300, paid in full.",
      "The statement is stale. The fix is provider posting, not an appeal.",
      "Official rule: allergy testing is 100% in network, limited to 1 testing (based on provider type).",
    ],
    modelMemberResponse:
      "Hi Hannah, I can see why the two letters were confusing. The first was a denial because the clinic made a coding mistake on its first claim. They fixed it, and your plan paid the testing in full on March 31. That's the second letter, and it shows you owe $0. Willow's bill still reflects the old denial, so please don't pay the $640. I'm sending their billing office the details of the corrected payment today so they can update your account, and I'll confirm it's cleared by next Tuesday.",
    conceptsToReview: ["claim-correction", "coding-error", "claim-statuses"],
  },
};

// =============================================================================
// CASE 12 · Intermediate+ · Benefit limit reached: partial payment + overbilling
// =============================================================================
export const case12: SimulationCaseInput = {
  id: "case-12-acupuncture-limit",
  version: 1,
  portfolioNumber: 12,
  code: "CASE-12",
  title: "Visit 21: when a benefit runs out",
  summary: "A multi-line acupuncture claim is partly paid because the 20-visit benefit was reached. The clinic's statement is also higher than the EOB.",
  scenario: "Partial payment: visit 20 paid, visits 21–22 not covered (plan maximum). The member does owe $190 per the EOB, but the statement asks for $265 because adjustments weren't applied.",
  recordingPriority: "medium",
  difficulty: "intermediate_plus",
  status: "ready",
  isSample: false,
  caseTypes: ["eob_investigation", "medical_billing", "denial"],
  skills: ["eob_reading", "member_responsibility", "allowed_amount", "billing_reconciliation", "inconsistency_detection", "plain_english", "denials"],
  knowledge: knowledge(
    ["rhus.benefit.acupuncture", "rhus.excl.plan_maximums", "rhus.cost.oop.never_counts", "rhus.cost.in_network_no_cost_share"],
    ["benefit-limit", "eob", "member-responsibility", "allowed-amount", "contracted-rate", "provider-statement", "out-of-pocket-max", "denial", "cpt", "icd10"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-10-27T12:09:00Z",
    memberMessage:
      "Harmony Acupuncture says I owe $265. My EOB shows two of my visits as \"not covered\"?? I thought acupuncture was covered on this plan. I've been going weekly for my neck since January.",
  },
  member: { name: "Diego Martínez", memberId: "RHU-60913-01", details: "Employee. Coverage began 01/01/2026." },
  plan: RHUS_PLAN,
  provider: { name: "Harmony Acupuncture", type: "Acupuncture clinic (fictional)", networkStatus: "in_network" },
  codes: [cpt("97810", "Acupuncture, one or more needles, without electrical stimulation, initial 15 minutes."), icd("M54.2", "Cervicalgia (neck pain).")],
  assumptions: [
    FICTION_ASSUMPTION,
    DOCS_ASSUMPTION,
    "The member had no acupuncture visits under the plan before 2026. All visits shown are in the member's first year of coverage.",
  ],
  documents: [
    { id: "doc-history", type: "note", title: "Benefit usage summary", provenance: caseFact(), author: "Claims system", date: "2026-10-27", body: "Acupuncture (97810) visits paid in 2026 before this claim: 19 (01/07 through 09/24)." },
    {
      id: "doc-claim",
      type: "claim",
      title: "Claim record",
      provenance: caseFact(),
      claimNumber: "CLM-26-1017-8840",
      status: "partially_denied",
      receivedDate: "2026-10-17",
      processedDate: "2026-10-22",
      billingProvider: "Harmony Acupuncture",
      networkStatus: "in_network",
      lines: [
        { dateOfService: "2026-10-01", code: "97810", diagnosisCodes: ["M54.2"], units: 1, charge: 12000, lineStatus: "Paid" },
        { dateOfService: "2026-10-08", code: "97810", diagnosisCodes: ["M54.2"], units: 1, charge: 12000, lineStatus: "Denied", denialReason: "MX1: Benefit maximum reached (20 visits)" },
        { dateOfService: "2026-10-15", code: "97810", diagnosisCodes: ["M54.2"], units: 1, charge: 12000, lineStatus: "Denied", denialReason: "MX1: Benefit maximum reached (20 visits)" },
      ],
    },
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-1017-8840",
      processedDate: "2026-10-22",
      patient: "Diego Martínez",
      provider: "Harmony Acupuncture",
      networkStatus: "in_network",
      lines: [
        eobLine({ dateOfService: "2026-10-01", service: "Acupuncture (visit 20)", code: "97810", benefitKey: "acupuncture", billed: 12000, allowed: 9500, planPaid: 9500 }),
        eobLine({ dateOfService: "2026-10-08", service: "Acupuncture (visit 21)", code: "97810", benefitKey: "acupuncture", billed: 12000, allowed: 9500, notCovered: 9500, memberResponsibility: 9500, remarkCodes: ["MX1"] }),
        eobLine({ dateOfService: "2026-10-15", service: "Acupuncture (visit 22)", code: "97810", benefitKey: "acupuncture", billed: 12000, allowed: 9500, notCovered: 9500, memberResponsibility: 9500, remarkCodes: ["MX1"] }),
      ],
      remarks: [{ code: "MX1", text: "Benefit maximum reached (20 visits). Amount is member responsibility." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Harmony Acupuncture",
      statementDate: "2026-10-25",
      accountNumber: "HA-7731",
      lines: [
        { dateOfService: "2026-10-01", description: "Acupuncture", code: "97810", charge: 12000 },
        { dateOfService: "2026-10-08", description: "Acupuncture", code: "97810", charge: 12000 },
        { dateOfService: "2026-10-15", description: "Acupuncture", code: "97810", charge: 12000 },
      ],
      insurancePayments: 9500,
      adjustments: 0,
      balanceDue: 26500,
    },
    planRulesDoc([
      ["Acupuncture", "rhus.benefit.acupuncture"],
      ["Plan maximums", "rhus.excl.plan_maximums"],
      ["Out-of-pocket limit exclusions", "rhus.cost.oop.never_counts"],
    ]),
  ],
  tasks: [
    choice("t-which", "Which visits on this claim exceeded the 20-visit acupuncture limit?", [["21-22", "10/08 and 10/15 (visits 21 and 22)"], ["all", "All three visits"], ["none", "None: the denial is an error"], ["20-21", "10/01 and 10/08"]], ["21-22"], { category: "plan_knowledge", points: 4, basis: [rule("rhus.benefit.acupuncture"), rule("rhus.excl.plan_maximums"), fact("doc-history"), assumed(2)], expectation: "Counts visits against the official 20-visit limit.", missed: "Official rules: acupuncture is limited to 20 visits, and costs above plan limits aren't covered. With 19 visits paid before, 10/01 is visit 20 (paid) and 10/08 and 10/15 are visits 21–22." }, "Visits 21 and 22."),
    amount("t-owed", "According to the EOB, what is the total member responsibility on this claim?", 19000, { category: "eob_interpretation", points: 4, basis: [fact("doc-eob")], expectation: "Totals the member-responsibility lines ($95 + $95).", missed: "Visit 20 = $0. Visits 21 and 22 = $95 each (their allowed amount). Total $190." }, "$190.00", { measures: "eob_member_responsibility" }),
    amount("t-overbill", "By how much does Harmony's balance exceed what the EOB supports?", 7500, { category: "eob_interpretation", points: 4, basis: [fact("doc-bill"), fact("doc-eob")], expectation: "Calculates $265 − $190 = $75.", missed: "The statement asks for $265 and the EOB supports $190, a $75 difference." }, "$75.00"),
    choice("t-why", "What explains the $75?", [["adj", "Harmony billed its full $120 charge per visit instead of the $95 allowed amount, so the $25 contractual adjustments (×3) weren't applied"], ["copay", "A per-visit provider charge for each visit"], ["deductible", "The member's deductible"], ["penalty", "A pre-authorization penalty"]], ["adj"], { category: "eob_interpretation", points: 3, basis: [concept("contracted-rate"), concept("allowed-amount"), fact("doc-bill")], expectation: "Identifies the missing adjustments.", missed: "Per the EOB, each visit's allowed amount is $95. The statement used the $120 charge for every visit and posted no adjustments. 3 × $25 = $75." }, "Missing contractual adjustments."),
    choice("t-oop", "Do the $190 in over-limit charges count toward the member's out-of-pocket limit?", [["no", "No: services not covered never count toward the out-of-pocket limit"], ["yes", "Yes: everything the member pays counts"], ["half", "Half of it counts"], ["unknown", "Only if the member asks"]], ["no"], { category: "plan_knowledge", points: 3, basis: [rule("rhus.cost.oop.never_counts")], expectation: "Applies the official accumulator rule.", missed: "Official rule: services not covered never count toward the out-of-pocket limit and are never covered at 100%." }, "No."),
    choice("t-codes", "Which pairing is correct?", [["right", "97810 = the acupuncture service; M54.2 = neck pain (the reason)"], ["rev", "97810 = neck pain; M54.2 = acupuncture"], ["mx1", "MX1 is the diagnosis"], ["both", "Both are diagnosis codes"]], ["right"], { category: "coding_understanding", points: 3, basis: [concept("cpt"), concept("icd10")], expectation: "Pairs CPT/ICD-10 correctly.", missed: "97810 (CPT) is what was done. M54.2 (ICD-10) is why." }, "97810 = service, M54.2 = reason."),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-limit", category: "claims_reasoning", points: 4, basis: [fact("doc-history"), fact("doc-eob"), rule("rhus.benefit.acupuncture"), rule("rhus.excl.plan_maximums")], expectation: "Explains the partial payment: visit 20 was paid, visits 21–22 exceeded the official 20-visit limit and aren't covered, so the EOB's $190 is correct.", missed: "Not every 'not covered' line is an error. Here the plan rule supports the partial denial." },
        { id: "c-overbill", category: "problem_solving", points: 3, basis: [fact("doc-bill"), concept("care-coordination"), concept("contracted-rate")], expectation: "Asks Harmony to correct the balance to $190 (apply the $75 in adjustments).", missed: "Even when the member owes something, the bill must match the EOB." },
        knownVsUnknown(2, "Notes that the source doesn't state the period for the 20-visit limit. It doesn't change this outcome (all visits fall in the first year of coverage), but questions about when it resets need verification.", [rule("rhus.benefit.acupuncture"), assumed(2)]),
      ],
      "Before this claim, 19 visits had been paid. On CLM-26-1017-8840, 10/01 (visit 20) was paid; 10/08 and 10/15 (visits 21–22) were denied for the benefit maximum. The official rules support this: 20 visits, and costs above plan limits aren't covered. Member responsibility is $190 ($95 × 2), and it doesn't count toward the out-of-pocket limit. Harmony's statement shows $265 because it used the $120 charge for every visit and posted no adjustments ($75). Ask Harmony to correct the balance to $190. Unknown: the period for the 20-visit limit, which the source doesn't state, so verify before telling the member when it resets.",
    ),
    memberReply({
      accuracy: "Explains that acupuncture is covered up to 20 visits, that two visits went past that so the member owes $190 for them per the plan's statement, and that the clinic's $265 is too high.",
      accuracyBasis: [fact("doc-eob"), rule("rhus.benefit.acupuncture")],
      promises: "Doesn't promise extra visits, an exception, or when the limit resets (the period isn't stated in the source).",
      next: "Says you're asking Harmony to correct the bill to $190, and suggests the member talk with the clinic about the cost of future visits.",
    }),
  ],
  debrief: {
    whatHappened:
      "After 19 paid visits, the 10/01 visit was the 20th and was paid. The 10/08 and 10/15 visits exceeded the 20-visit limit and were not covered ($95 each, $190 total). Harmony's statement charged its full price for all three visits without adjustments: $265.",
    correctReasoning: [
      "Official rules: acupuncture is limited to 20 visits, and costs above plan limits aren't covered.",
      "The partial payment is correct: $0 for visit 20, $95 each for visits 21–22.",
      "Official rule: non-covered amounts never count toward the out-of-pocket limit.",
      "The statement is $75 too high because the contractual adjustments weren't applied.",
      "The source doesn't state the limit's time period, so don't guess when it resets.",
    ],
    modelMemberResponse:
      "Hi Diego, good question. Acupuncture is covered on your plan, but only up to 20 visits. Your October 1 visit was number 20 and was paid in full. The October 8 and 15 visits went past the limit, so the plan didn't cover them, and your plan's statement shows $190 for those two. Harmony's bill of $265 is higher than that, so I'm asking them to correct it to $190. Please wait for the corrected bill before paying. Since future visits won't be covered, it's worth asking Harmony what they'd cost before your next appointment. I'll update you by Friday.",
    conceptsToReview: ["benefit-limit", "contracted-rate", "out-of-pocket-max"],
  },
};
