import type { SimulationCaseInput } from "@/domain/case";
import { caseFact } from "@/domain/provenance";
import {
  DOCS_ASSUMPTION, FICTION_ASSUMPTION, INVESTIGATION_PROMPT, RHUS_PLAN, amount, choice, concept, cpt, eobLine, fact, icd,
  investigation, knowledge, knownVsUnknown, memberReply, planRulesDoc, rule, selectAll,
} from "./helpers";

// =============================================================================
// CASE 09 · Intermediate+ · Duplicate denial and an unposted payment
// =============================================================================
export const case09: SimulationCaseInput = {
  id: "case-09-duplicate-denial",
  version: 1,
  portfolioNumber: 9,
  code: "CASE-09",
  title: "\"DENIED as a duplicate?\": the colonoscopy that was already paid",
  summary: "A pre-authorized colonoscopy was paid, then resubmitted and denied as a duplicate. The provider bills the full charge.",
  scenario: "Two claims and two EOBs. The original was paid in full and the resubmission denied as a duplicate. The provider's statement ignores the original payment and adjustment.",
  recordingPriority: "medium",
  difficulty: "intermediate_plus",
  status: "ready",
  isSample: false,
  caseTypes: ["claims_investigation", "denial", "medical_billing"],
  skills: ["claim_status", "denials", "billing_reconciliation", "inconsistency_detection", "prior_auth", "provider_communication"],
  knowledge: knowledge(
    ["rhus.benefit.endoscopy_non_routine", "rhus.cost.in_network_no_cost_share"],
    ["duplicate-claim", "claim-statuses", "denial", "eob", "provider-statement", "prior-authorization", "authorization-linking", "contracted-rate", "cpt", "icd10"],
  ),
  ticket: {
    channel: "chat",
    receivedAt: "2026-05-06T10:12:00Z",
    memberMessage:
      "Hi, I got an EOB that says my colonoscopy claim was DENIED as a \"duplicate\"?? And Bayside just sent me a bill for $2,400. I had approval for this procedure! Do I have to pay?",
  },
  member: { name: "Robert Chen", memberId: "RHU-33019-01", details: "Employee" },
  plan: RHUS_PLAN,
  provider: { name: "Bayside Gastroenterology", type: "Gastroenterology practice and endoscopy suite (fictional)", networkStatus: "in_network" },
  codes: [cpt("45378", "Diagnostic colonoscopy."), icd("K92.1", "Melena (dark, tarry stools).")],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION],
  documents: [
    {
      id: "doc-auth",
      type: "authorization",
      title: "Authorization record",
      provenance: caseFact(),
      authNumber: "AUTH-2026-022610",
      status: "approved",
      service: "Diagnostic colonoscopy",
      codes: ["45378"],
      diagnosisCodes: ["K92.1"],
      requestingProvider: "Bayside Gastroenterology",
      servicingProvider: "Bayside Gastroenterology",
      decisionDate: "2026-02-26",
      validFrom: "2026-03-01",
      validTo: "2026-04-30",
      requirement: { benefitKey: "endoscopy_non_routine", required: true },
    },
    {
      id: "doc-claim-1",
      type: "claim",
      title: "Claim record: CLM-26-0314-4402 (original)",
      provenance: caseFact(),
      claimNumber: "CLM-26-0314-4402",
      status: "processed_paid",
      receivedDate: "2026-03-14",
      processedDate: "2026-03-27",
      billingProvider: "Bayside Gastroenterology",
      networkStatus: "in_network",
      authorizationNumberOnClaim: "AUTH-2026-022610",
      lines: [{ dateOfService: "2026-03-11", code: "45378", diagnosisCodes: ["K92.1"], units: 1, charge: 240000, lineStatus: "Paid. Payment issued 03/27 (EFT ref 77-1904)" }],
    },
    {
      id: "doc-claim-2",
      type: "claim",
      title: "Claim record: CLM-26-0420-1189 (resubmission)",
      provenance: caseFact(),
      claimNumber: "CLM-26-0420-1189",
      status: "denied",
      receivedDate: "2026-04-20",
      processedDate: "2026-04-28",
      billingProvider: "Bayside Gastroenterology",
      networkStatus: "in_network",
      authorizationNumberOnClaim: "AUTH-2026-022610",
      lines: [{ dateOfService: "2026-03-11", code: "45378", diagnosisCodes: ["K92.1"], units: 1, charge: 240000, lineStatus: "Denied", denialReason: "DUP: Duplicate of claim CLM-26-0314-4402" }],
    },
    {
      id: "doc-eob-1",
      type: "eob",
      title: "Explanation of Benefits: CLM-26-0314-4402",
      provenance: caseFact(),
      claimNumber: "CLM-26-0314-4402",
      processedDate: "2026-03-27",
      patient: "Robert Chen",
      provider: "Bayside Gastroenterology",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-03-11", service: "Colonoscopy", code: "45378", benefitKey: "endoscopy_non_routine", billed: 240000, allowed: 110000, planPaid: 110000 })],
      remarks: [{ code: "A1", text: "Authorization AUTH-2026-022610 applied." }],
    },
    {
      id: "doc-eob-2",
      type: "eob",
      title: "Explanation of Benefits: CLM-26-0420-1189",
      provenance: caseFact(),
      claimNumber: "CLM-26-0420-1189",
      processedDate: "2026-04-28",
      patient: "Robert Chen",
      provider: "Bayside Gastroenterology",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-03-11", service: "Colonoscopy", code: "45378", benefitKey: "endoscopy_non_routine", billed: 240000, remarkCodes: ["DUP"] })],
      remarks: [{ code: "DUP", text: "This claim duplicates claim CLM-26-0314-4402, which was already processed. Member responsibility: $0.00." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Bayside Gastroenterology",
      statementDate: "2026-05-02",
      accountNumber: "BG-660218",
      lines: [{ dateOfService: "2026-03-11", description: "Colonoscopy, diagnostic", code: "45378", charge: 240000 }],
      insurancePayments: 0,
      adjustments: 0,
      balanceDue: 240000,
      message: "Insurance denied claim (duplicate). Balance due from patient.",
    },
    planRulesDoc([
      ["Endoscopic tests (non-routine)", "rhus.benefit.endoscopy_non_routine"],
      ["In-network cost sharing", "rhus.cost.in_network_no_cost_share"],
    ]),
  ],
  tasks: [
    choice("t-original", "Which claim is the original, and what happened to it?", [["c1-paid", "CLM-26-0314-4402: paid in full on 03/27"], ["c2-paid", "CLM-26-0420-1189: paid"], ["both-denied", "Both were denied"], ["c1-pending", "CLM-26-0314-4402: still pending"]], ["c1-paid"], { category: "claims_reasoning", points: 4, basis: [fact("doc-claim-1"), fact("doc-eob-1"), concept("claim-statuses")], expectation: "Finds the original, paid claim.", missed: "Match by date of service and code. The 03/14 claim was paid on 03/27. The 04/20 claim is a resubmission of the same service." }, "CLM-26-0314-4402, paid."),
    choice("t-dup", "What does the duplicate denial mean?", [["dup", "The second submission was rejected because the same service was already processed. It's not a coverage denial."], ["notcovered", "Colonoscopy isn't covered"], ["noauth", "The authorization wasn't valid"], ["member", "The member must now pay the full charge"]], ["dup"], { category: "claims_reasoning", points: 3, basis: [fact("doc-eob-2"), concept("duplicate-claim")], expectation: "Explains duplicate denials correctly.", missed: "A duplicate denial stops double payment. It says nothing about coverage, and its EOB shows $0 member responsibility." }, "A repeat submission was rejected; the original stands."),
    amount("t-owed", "Across both EOBs, what is the member responsibility for this colonoscopy?", 0, { category: "eob_interpretation", points: 4, basis: [fact("doc-eob-1"), fact("doc-eob-2")], expectation: "Reads $0.00 on both EOBs.", missed: "Both EOBs show $0.00 member responsibility." }, "$0.00", { measures: "eob_member_responsibility" }),
    amount("t-paid", "How much did the plan pay Bayside on the original claim?", 110000, { category: "eob_interpretation", points: 3, basis: [fact("doc-eob-1")], expectation: "Reads plan paid $1,100.00.", missed: "The original EOB shows plan paid $1,100.00, the full allowed amount." }, "$1,100.00"),
    choice("t-pa", "What is the pre-authorization situation?", [["ok", "Required (non-routine endoscopy) and approved; the authorization number is on the claims"], ["notreq", "Not required for colonoscopy"], ["missing", "Required but missing, which caused the denial"], ["expired", "Expired before the procedure"]], ["ok"], { category: "prior_authorization", points: 4, basis: [rule("rhus.benefit.endoscopy_non_routine"), fact("doc-auth"), fact("doc-claim-1")], expectation: "Confirms authorization is not the issue.", missed: "Official rule: non-routine endoscopic tests require pre-authorization. AUTH-2026-022610 was approved, valid on 03/11, and linked. The denial is about duplication, not authorization." }, "Required, approved and linked: not the issue."),
    selectAll(
      "t-bill",
      "Which statements explain why Bayside's $2,400 statement is wrong? Select all that apply.",
      [["no-payment", "It doesn't show the plan's $1,100 payment from 03/27"], ["dup", "It reflects the duplicate denial instead of the original, paid claim"], ["no-adj", "It doesn't apply the $1,300 contractual adjustment (billed − allowed)"], ["owes", "The member owes the full $2,400 because a claim was denied"]],
      ["no-payment", "dup", "no-adj"],
      { category: "eob_interpretation", points: 4, basis: [fact("doc-bill"), fact("doc-eob-1"), fact("doc-eob-2"), concept("contracted-rate")], expectation: "Explains the statement error fully.", missed: "Bayside appears to have resubmitted because it never posted the original payment. The statement should show $1,100 paid, $1,300 adjusted and $0 due." },
      "No payment posted, wrong claim referenced, no adjustment.",
    ),
    choice("t-codes", "Which pairing is correct?", [["right", "45378 = procedure (colonoscopy); K92.1 = diagnosis (dark stools)"], ["rev", "45378 = diagnosis; K92.1 = procedure"], ["auth", "K92.1 is the authorization code"], ["dup", "DUP is the diagnosis"]], ["right"], { category: "coding_understanding", points: 4, basis: [concept("cpt"), concept("icd10")], expectation: "Pairs CPT/ICD correctly.", missed: "45378 (CPT) is what was done. K92.1 (ICD-10) is why." }, "45378 = procedure, K92.1 = diagnosis."),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-root", category: "claims_reasoning", points: 4, basis: [fact("doc-claim-1"), fact("doc-claim-2"), fact("doc-bill"), concept("duplicate-claim")], expectation: "Explains that the original claim was paid in full on 03/27. Bayside resubmitted on 04/20 (likely because the payment wasn't posted on their side), and the resubmission was correctly denied as a duplicate. The statement is based on the wrong claim.", missed: "Reconstruct the timeline from the two claims. The duplicate denial is a symptom; the root issue is on the provider's posting side." },
        { id: "c-coord", category: "problem_solving", points: 4, basis: [concept("care-coordination"), fact("doc-eob-1")], expectation: "Contacts Bayside's billing office with the original claim number, payment date and EFT reference, and asks them to post the $1,100 payment and $1,300 adjustment and zero the balance. Notes that no correction or appeal of the duplicate is needed.", missed: "Give the provider what they need to find the payment. The fix is posting, not reprocessing." },
        knownVsUnknown(2, "Labels the provider-posting explanation as the likely cause, not a confirmed fact, until Bayside confirms.", [fact("doc-bill")]),
      ],
      "Original claim CLM-26-0314-4402 (45378, K92.1, authorized under AUTH-2026-022610) was paid on 03/27: allowed $1,100, plan paid $1,100, member $0. Bayside resubmitted the same service on 04/20, and it was correctly denied as a duplicate ($0 member responsibility). Bayside's statement shows the full $2,400 as if nothing was paid, probably because the 03/27 payment wasn't posted. Contact Bayside billing with the claim number, payment date and EFT ref 77-1904. They should post $1,100 paid and the $1,300 adjustment, leaving $0. No appeal or correction is needed.",
    ),
    memberReply({
      accuracy: "Explains that the colonoscopy was approved and paid in full in March, that the 'duplicate' notice was for a second copy of the same claim, and that the member owes $0 per both statements.",
      accuracyBasis: [fact("doc-eob-1"), fact("doc-eob-2")],
      promises: "Doesn't promise exactly when Bayside will fix its records. Says what you're doing.",
      next: "Asks the member not to pay the $2,400. Says you're contacting Bayside with the payment details and gives a follow-up time.",
    }),
  ],
  debrief: {
    whatHappened:
      "The colonoscopy was pre-authorized and paid in full on 03/27. Bayside resubmitted the same claim on 04/20, most likely because it hadn't posted the payment, and the resubmission was denied as a duplicate. Bayside then billed the member the full charge.",
    correctReasoning: [
      "Two claims, same service and date: the first was paid, the second correctly denied as a duplicate.",
      "A duplicate denial isn't a coverage denial, and both EOBs show $0 member responsibility.",
      "Official rule: non-routine endoscopy requires pre-authorization. It was approved and linked, so it's not the issue.",
      "The statement is missing the $1,100 payment and $1,300 adjustment.",
      "The fix is provider payment posting, not an appeal or a corrected claim.",
    ],
    modelMemberResponse:
      "Hi Robert, I can see why 'denied' was alarming, but good news: your colonoscopy was approved and your plan paid it in full back in March. The 'duplicate' notice is because Bayside sent the same claim a second time, and the plan correctly rejected the copy. Both statements from your plan show you owe $0. It looks like Bayside's records don't show the March payment yet, so please don't pay the $2,400. I'm contacting their billing office today with the payment details so they can update your account, and I'll confirm with you by Thursday.",
    conceptsToReview: ["duplicate-claim", "provider-statement", "claim-statuses"],
  },
};

// =============================================================================
// CASE 10 · Intermediate+ · Expired authorization + overbilling
// =============================================================================
export const case10: SimulationCaseInput = {
  id: "case-10-expired-auth",
  version: 1,
  portfolioNumber: 10,
  code: "CASE-10",
  title: "Expired authorization, and a bill that's still too high",
  summary: "The facility rescheduled an MRI past the authorization's end date. The plan applied the 10% reduction, and the facility billed far more than the EOB.",
  scenario: "Two separate issues. (1) Expired authorization: the official 10% reduction = $135. (2) The statement adds a $750 contractual adjustment the EOB doesn't support ($885 vs $135).",
  recordingPriority: "high",
  difficulty: "intermediate_plus",
  status: "ready",
  isSample: false,
  caseTypes: ["prior_authorization", "medical_billing", "eob_investigation"],
  skills: ["prior_auth", "member_responsibility", "allowed_amount", "billing_reconciliation", "inconsistency_detection", "provider_communication"],
  knowledge: knowledge(
    ["rhus.benefit.diagnostic_mri", "rhus.pa.list.k", "rhus.pa.penalty", "rhus.pa.penalty_not_counted", "rhus.pa.member_must_confirm", "rhus.cost.in_network_no_cost_share"],
    ["prior-authorization", "authorization-linking", "allowed-amount", "contracted-rate", "provider-statement", "member-responsibility", "eob", "cpt", "icd10"],
  ),
  ticket: {
    channel: "email",
    receivedAt: "2026-05-04T07:55:00Z",
    memberMessage:
      "Hello, Eastside Imaging is charging me $885 for my shoulder MRI. The EOB says something about an expired authorization?? I didn't even choose the date: the imaging center moved my appointment! This doesn't seem fair. — Nora",
  },
  member: { name: "Nora Whitfield", memberId: "RHU-47720-01", details: "Employee" },
  plan: RHUS_PLAN,
  provider: { name: "Eastside Diagnostic Imaging", type: "Outpatient imaging center (fictional)", networkStatus: "in_network" },
  codes: [cpt("73221", "MRI of a shoulder (upper-extremity joint) without contrast."), icd("M75.121", "Complete rotator cuff tear or rupture, right shoulder, not specified as traumatic.")],
  assumptions: [FICTION_ASSUMPTION, DOCS_ASSUMPTION, "The EOB shows the pre-authorization reduction as a 'not covered' amount. That presentation is simulated."],
  documents: [
    {
      id: "doc-auth",
      type: "authorization",
      title: "Authorization record",
      provenance: caseFact(),
      authNumber: "AUTH-2026-030455",
      status: "expired",
      service: "MRI right shoulder without contrast",
      codes: ["73221"],
      diagnosisCodes: ["M75.121"],
      requestingProvider: "Dr. Kevin Marsh (Orthopedics)",
      servicingProvider: "Eastside Diagnostic Imaging",
      decisionDate: "2026-02-27",
      validFrom: "2026-03-01",
      validTo: "2026-03-31",
      notes: "Approved 02/27, valid 03/01–03/31. No extension or new request on file.",
      requirement: { benefitKey: "diagnostic_mri", required: true },
    },
    { id: "doc-schedule", type: "note", title: "Scheduling note (from Eastside)", provenance: caseFact(), author: "Eastside Diagnostic Imaging", date: "2026-03-25", body: "Patient appointment 03/27 cancelled by facility (scanner maintenance). Rescheduled to 04/03." },
    {
      id: "doc-claim",
      type: "claim",
      title: "Claim record",
      provenance: caseFact(),
      claimNumber: "CLM-26-0407-3361",
      status: "processed_paid",
      receivedDate: "2026-04-07",
      processedDate: "2026-04-18",
      billingProvider: "Eastside Diagnostic Imaging",
      networkStatus: "in_network",
      authorizationNumberOnClaim: "AUTH-2026-030455",
      lines: [{ dateOfService: "2026-04-03", code: "73221", diagnosisCodes: ["M75.121"], units: 1, charge: 210000, lineStatus: "Paid with reduction (PA03)" }],
    },
    {
      id: "doc-eob",
      type: "eob",
      title: "Explanation of Benefits",
      provenance: caseFact(),
      claimNumber: "CLM-26-0407-3361",
      processedDate: "2026-04-18",
      patient: "Nora Whitfield",
      provider: "Eastside Diagnostic Imaging",
      networkStatus: "in_network",
      lines: [eobLine({ dateOfService: "2026-04-03", service: "MRI shoulder", code: "73221", benefitKey: "diagnostic_mri", billed: 210000, allowed: 135000, planPaid: 121500, notCovered: 13500, memberResponsibility: 13500, remarkCodes: ["PA03"] })],
      remarks: [{ code: "PA03", text: "The authorization on file ended before the date of service. Covered charges reduced by 10% (maximum $500). Not applied to the deductible or out-of-pocket maximum." }],
    },
    {
      id: "doc-bill",
      type: "provider_bill",
      title: "Provider statement",
      provenance: caseFact(),
      providerName: "Eastside Diagnostic Imaging",
      statementDate: "2026-04-28",
      accountNumber: "EDI-90311",
      lines: [{ dateOfService: "2026-04-03", description: "MRI shoulder w/o contrast", code: "73221", charge: 210000 }],
      insurancePayments: 121500,
      adjustments: 0,
      balanceDue: 88500,
    },
    planRulesDoc([
      ["MRI benefit", "rhus.benefit.diagnostic_mri"],
      ["Pre-authorization list", "rhus.pa.list.k"],
      ["Missing pre-authorization", "rhus.pa.penalty"],
      ["Penalty and accumulators", "rhus.pa.penalty_not_counted"],
      ["Member's responsibility", "rhus.pa.member_must_confirm"],
    ]),
  ],
  tasks: [
    choice("t-window", "How does the date of service compare with the authorization?", [["after", "It falls after the authorization ended (valid through 03/31; scan on 04/03)"], ["inside", "It's inside the validity window"], ["before", "It's before the authorization started"], ["no-auth", "There was never an authorization"]], ["after"], { category: "prior_authorization", points: 3, basis: [fact("doc-auth"), fact("doc-claim"), concept("authorization-linking")], expectation: "Compares the date of service to the validity window.", missed: "AUTH-2026-030455 was valid 03/01–03/31. The scan happened 04/03, three days after it ended." }, "After it expired."),
    amount("t-penalty", "Using the official rule, what reduction applies to $1,350 of covered charges?", 13500, { category: "plan_knowledge", points: 4, basis: [rule("rhus.pa.penalty"), fact("doc-eob")], expectation: "Calculates 10% × $1,350 = $135.", missed: "Official rule: covered charges are reduced by 10%, up to $500. 10% of the $1,350 allowed amount = $135." }, "$135.00"),
    amount("t-owed", "According to the EOB, what is the member responsibility?", 13500, { category: "eob_interpretation", points: 3, basis: [fact("doc-eob")], expectation: "Reads $135.00.", missed: "The EOB shows $135.00. The plan paid $1,215 of the $1,350 allowed." }, "$135.00", { measures: "eob_member_responsibility" }),
    amount("t-overbill", "By how much does Eastside's balance exceed what the EOB supports?", 75000, { category: "eob_interpretation", points: 4, basis: [fact("doc-bill"), fact("doc-eob")], expectation: "Calculates $885 − $135 = $750.", missed: "The statement's balance is $885. The EOB supports $135. The difference is $750." }, "$750.00"),
    choice("t-why-overbill", "What explains the $750 difference?", [["adj", "Eastside didn't apply the contractual adjustment (billed $2,100 − allowed $1,350 = $750)"], ["penalty", "A second pre-authorization penalty"], ["deductible", "The member's deductible"], ["oon", "Out-of-network balance billing"]], ["adj"], { category: "eob_interpretation", points: 3, basis: [concept("contracted-rate"), concept("allowed-amount"), fact("doc-bill")], expectation: "Identifies the missing contractual write-off.", missed: "In network, the amount above the allowed amount is written off. The statement shows $0 in adjustments, so the $750 write-off is missing. The provider is in network, so this isn't balance billing." }, "The missing contractual adjustment."),
    choice("t-schedule", "What does the scheduling note add to the investigation?", [["context", "The facility moved the appointment past the authorization end date. That's relevant to raise with the provider and administrator, but it doesn't change the outcome on its own."], ["fault", "It proves the member is at fault"], ["paid-wrong", "It proves the claim must be paid in full"], ["irrelevant", "Nothing: scheduling doesn't matter"]], ["context"], { category: "problem_solving", points: 3, basis: [fact("doc-schedule"), rule("rhus.pa.member_must_confirm")], expectation: "Uses the note as context without over-concluding.", missed: "The note explains how the authorization lapsed and gives you something to raise. The sources don't say it reverses the reduction, so don't promise that." }, "Relevant context; outcome unverified."),
    selectAll(
      "t-codes",
      "Select every true statement.",
      [["proc", "73221 is the procedure performed"], ["dx", "M75.121 explains why the MRI was done"], ["match", "The codes on the authorization match the codes on the claim"], ["mismatch", "A coding mismatch caused the reduction"]],
      ["proc", "dx", "match"],
      { category: "coding_understanding", points: 4, basis: [concept("cpt"), concept("icd10"), fact("doc-auth"), fact("doc-claim")], expectation: "Separates code roles and rules out a coding cause.", missed: "The codes match. The problem is the date, not coding. Check codes, dates and provider separately." },
      "73221 = procedure, M75.121 = reason, codes match.",
    ),
    investigation(
      INVESTIGATION_PROMPT,
      [
        { id: "c-two-issues", category: "claims_reasoning", points: 5, basis: [fact("doc-auth"), fact("doc-eob"), fact("doc-bill"), rule("rhus.pa.penalty")], expectation: "Separates the two issues: (1) the scan fell after the authorization ended, so the official 10% reduction ($135) was applied; (2) the statement is $750 too high because the contractual adjustment wasn't applied. The correct balance per the EOB is $135.", missed: "Multi-issue cases need each issue named separately. Fixing only the overbilling or only the authorization question leaves the member with a wrong answer." },
        knownVsUnknown(3, "Notes what's unknown: whether anything can be reviewed given the facility-initiated reschedule. The sources are silent, so this is raised with the administrator without any promise.", [fact("doc-schedule"), fact("doc-auth")]),
        { id: "c-contacts", category: "problem_solving", points: 3, basis: [concept("care-coordination"), concept("contracted-rate")], expectation: "Contacts: Eastside billing to apply the $750 adjustment (balance → $135); Eastside/ordering office about the reschedule past the authorization end date; the claims administrator about whether anything can be reviewed.", missed: "Each issue has its own owner: billing errors go to the provider's billing office, and authorization questions go to the provider and administrator." },
      ],
      "AUTH-2026-030455 for 73221/M75.121 was valid 03/01–03/31. Eastside cancelled the 03/27 appointment and rescheduled it to 04/03, after the authorization ended, and no extension is on file. The claim was paid with the official reduction: 10% of $1,350 = $135 (doesn't count toward the deductible or out-of-pocket maximum). Separately, Eastside's statement shows $885 because it didn't apply the $750 contractual adjustment. Per the EOB, the balance should be $135. Actions: ask Eastside billing to correct the balance to $135. Raise the facility-initiated reschedule with Eastside and the ordering office, and ask the claims administrator whether it can be reviewed, without promising a result.",
    ),
    memberReply({
      accuracy: "Explains both findings: the bill is too high (the plan's statement supports $135, not $885), and the $135 comes from the approval expiring before the rescheduled scan date.",
      accuracyBasis: [fact("doc-eob"), fact("doc-bill"), fact("doc-auth")],
      promises: "Doesn't promise the $135 will be removed because the facility rescheduled. Says you'll raise it.",
      next: "Asks the member not to pay $885. Says you're getting the bill corrected and raising the reschedule issue, with a follow-up date.",
      empathy: "Acknowledges the unfairness the member feels, since the facility moved the date.",
    }),
  ],
  debrief: {
    whatHappened:
      "Eastside moved the MRI from 03/27 to 04/03, after the authorization ended on 03/31. The plan applied its 10% reduction ($135). Eastside's statement also failed to apply the $750 contractual adjustment, so it asks for $885 instead of $135.",
    correctReasoning: [
      "The date of service falls outside the validity window: an expired authorization.",
      "Official rule: covered charges reduced 10%, up to $500. 10% of $1,350 = $135. It doesn't count toward the deductible or out-of-pocket maximum.",
      "The statement's $885 vs. the EOB's $135: a $750 missing contractual adjustment (billed − allowed).",
      "The codes match the authorization, so the issue is the date, not the coding.",
      "The facility's reschedule is a legitimate point to raise, but the sources don't say it reverses the reduction.",
    ],
    modelMemberResponse:
      "Hi Nora, I understand, it's frustrating to be penalized for a date you didn't choose. I found two things. First, the bill is too high: based on your plan's statement, the most you could owe is $135, not $885. Eastside left out a discount they're required to apply, and I'm asking them to correct it. Second, the $135 comes from your MRI approval ending on March 31, three days before the rescheduled scan. When that happens, the plan reduces what it pays by 10%. Since Eastside moved your appointment, I'm raising that with them and with the claims team, though I can't promise it will change. Please don't pay the $885. I'll update you by next Wednesday.",
    conceptsToReview: ["authorization-linking", "contracted-rate", "allowed-amount"],
  },
};
