import type { BenefitInput, Coverage } from "@/domain/plan-knowledge";
import { bo } from "./rules";

/**
 * Remote Health USA benefits, one entry per benefit row of the benefits overview.
 * Where the user-facing topic is narrower than the source row (e.g. MRI within
 * "Diagnostic testing"), several entries cite the same row.
 */

const IN_100: Coverage = { planPaysPct: 100, afterDeductible: false, label: "100%" };
const OON_100: Coverage = { planPaysPct: 100, afterDeductible: false, label: "100%" };
const OON_70: Coverage = { planPaysPct: 70, afterDeductible: true, label: "70% after deductible" };
const NOT_COVERED: Coverage = { planPaysPct: null, afterDeductible: false, label: "Not covered" };

const DIAGNOSTIC_ROW = bo(5, "Doctors and specialists", "Diagnostic testing 100% 70% after deductible (X-ray, MRI, CT, PET scans, labs) Pre-authorization required");
const MH_ROW = bo(6, "Specialty support", "Mental and substance use disorders 100% 70% after deductible While hospitalized, office or virtual visit Pre-authorization required");
const THERAPY_ROW = bo(6, "Specialty support", "Physical, speech and occupational therapies 100% 70% after deductible Including virtual visits");

export const rhusBenefits: BenefitInput[] = [
  // Emergency ---------------------------------------------------------------
  {
    key: "emergency_services",
    label: "Emergency services: emergency medical condition",
    group: "emergency",
    inNetwork: IN_100,
    outOfNetwork: OON_100,
    preAuth: "notification",
    preAuthNote:
      "Row says 'Pre-authorization required (see pre-authorization section for details)'. That section requires a call within 24 hours of an emergency admission (72 hours on weekends/holidays).",
    citation: bo(3, "In case of emergency", "For emergency medical condition 100% 100% Pre-authorization required (see pre-authorization section for details)"),
    status: "confirmed",
  },
  {
    key: "emergency_room_non_emergency",
    label: "Emergency services: non-emergency medical condition",
    group: "emergency",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthNote: "Marked 'Pre-authorization required' in the benefits table but not named on the A–T pre-authorization list.",
    citation: bo(3, "In case of emergency", "For non-emergency medical condition 100% 70% after deductible Pre-authorization required"),
    status: "needs_clarification",
  },
  {
    key: "ambulance_emergency",
    label: "Emergency ambulance",
    group: "emergency",
    inNetwork: IN_100,
    outOfNetwork: OON_100,
    limits: "Up to $25,000 for each air/water ambulance ride",
    preAuth: "required_partial",
    preAuthListRefs: ["O"],
    preAuthNote: "Air/water ambulance requires pre-authorization. Ground ambulance is not listed.",
    citation: bo(3, "In case of emergency", "Emergency ambulance 100% 100% Up to $25,000 for each air/water ambulance ride, pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "ambulance_non_emergency",
    label: "Non-emergency ambulance (water, air, ground)",
    group: "emergency",
    inNetwork: NOT_COVERED,
    outOfNetwork: NOT_COVERED,
    preAuth: "not_stated",
    specialConditions: "Except as covered under emergency ambulance.",
    citation: bo(3, "In case of emergency", "Non-emergency ambulance Not covered Not covered Water, air, ground Except as covered under emergency ambulance"),
    status: "confirmed",
    note: "p.2 separately says non-emergency ambulance counts toward the in-network out-of-pocket limit (see rhus.cost.oop.in_network_contributors).",
  },
  {
    key: "urgent_care",
    label: "Urgent care facility",
    group: "emergency",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthNote: "Marked 'Pre-authorization required' in the benefits table but not named on the A–T pre-authorization list. Pre-authorizing urgent care is unusual, so confirm with the SPD before relying on it.",
    citation: bo(3, "In case of emergency", "Urgent care facility 100% 70% after deductible Pre-authorization required"),
    status: "needs_clarification",
  },
  // Hospital ----------------------------------------------------------------
  {
    key: "hospital_room",
    label: "Hospital stay (semi-private room)",
    group: "hospital",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["A", "C"],
    specialConditions: "A private room is covered only if medically necessary. If the hospital only has private rooms, coverage is limited to the lowest private-room rate.",
    citation: bo(
      3,
      "Hospital charges",
      "Semi-private room when hospitalized 100% 70% after deductible A private room is covered only if it's medically Pre-authorization required necessary. If the hospital only has private rooms, coverage is limited to the lowest private room rate.",
    ),
    status: "confirmed",
  },
  {
    key: "physician_services_hospital",
    label: "Physician services (hospital charges)",
    group: "hospital",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(3, "Hospital charges", "Physician's services 100% 70% after deductible"),
    status: "confirmed",
  },
  {
    key: "icu",
    label: "Intensive care unit",
    group: "hospital",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["A"],
    specialConditions: "The plan pays the ICU rate.",
    citation: bo(4, "Hospital charges", "Intensive care unit 100% 70% after deductible This plan pays the ICU rate Pre-authorization required"),
    status: "confirmed",
  },
  // Surgery -----------------------------------------------------------------
  {
    key: "surgery",
    label: "Surgery",
    group: "surgery",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["A", "F", "J"],
    citation: bo(4, "Hospital charges", "Surgery 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "day_surgery",
    label: "Day surgery",
    group: "surgery",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["J"],
    citation: bo(4, "Hospital charges", "Day surgery 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "oral_surgery",
    label: "Oral surgery",
    group: "surgery",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["J"],
    citation: bo(4, "Hospital charges", "Oral surgery 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
    note: "Routine dental care is excluded unless related to a covered medical procedure (p.12). Dental is a separate add-on.",
  },
  {
    key: "wisdom_teeth",
    label: "Extraction of impacted wisdom teeth",
    group: "surgery",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    citation: bo(4, "Hospital charges", "Extraction of impacted wisdom teeth 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "endoscopy_non_routine",
    label: "Endoscopic tests (non-routine)",
    group: "surgery",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["J"],
    citation: bo(4, "Hospital charges", "Endoscopic tests (non-routine) 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "second_surgical_opinion",
    label: "Second surgical opinion",
    group: "surgery",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(4, "Hospital charges", "Second surgical opinion 100% 70% after deductible"),
    status: "confirmed",
  },
  // Physician ---------------------------------------------------------------
  {
    key: "pcp_visit",
    label: "Primary care doctor (PCP) visit",
    group: "physician",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(5, "Doctors and specialists", "Primary care doctor (PCP) visit 100% 70% after deductible"),
    status: "confirmed",
  },
  {
    key: "specialist_visit",
    label: "Specialist doctor visit",
    group: "physician",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(5, "Doctors and specialists", "Specialist doctor visit 100% 70% after deductible"),
    status: "confirmed",
  },
  {
    key: "walk_in_clinic",
    label: "Walk-in clinic",
    group: "physician",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(5, "Doctors and specialists", "Walk-in clinic 100% 70% after deductible"),
    status: "confirmed",
  },
  {
    key: "private_duty_nursing",
    label: "Private duty nursing (outpatient)",
    group: "physician",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "60 visits a year",
    preAuth: "required",
    preAuthListRefs: ["J"],
    citation: bo(5, "Doctors and specialists", "Private duty nursing (outpatient) 100% 70% after deductible 60 visits a year Pre-authorization required"),
    status: "confirmed",
  },
  // Diagnostics -------------------------------------------------------------
  {
    key: "diagnostic_mri",
    label: "MRI",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["K"],
    citation: DIAGNOSTIC_ROW,
    status: "confirmed",
  },
  {
    key: "diagnostic_ct",
    label: "CT scan",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["K"],
    citation: DIAGNOSTIC_ROW,
    status: "confirmed",
  },
  {
    key: "diagnostic_pet",
    label: "PET scan",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["K"],
    citation: DIAGNOSTIC_ROW,
    status: "confirmed",
  },
  {
    key: "diagnostic_xray",
    label: "X-ray",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "unclear",
    preAuthNote:
      "The 'Diagnostic testing' row (X-ray, MRI, CT, PET scans, labs) is marked 'Pre-authorization required', but the pre-authorization list names only 'Diagnostic testing (MRI/PET/CT)'.",
    citation: DIAGNOSTIC_ROW,
    status: "needs_clarification",
  },
  {
    key: "diagnostic_labs",
    label: "Lab tests",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "unclear",
    preAuthNote:
      "The 'Diagnostic testing' row (X-ray, MRI, CT, PET scans, labs) is marked 'Pre-authorization required', but the pre-authorization list names only 'Diagnostic testing (MRI/PET/CT)'.",
    citation: DIAGNOSTIC_ROW,
    status: "needs_clarification",
  },
  {
    key: "genetic_testing",
    label: "Genetic testing",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["N"],
    citation: bo(5, "Doctors and specialists", "Genetic testing 100% 70% after deductible (e.g., BRACA, BART) Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "allergy_testing",
    label: "Allergy testing",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "1 testing (based on provider type)",
    preAuth: "not_stated",
    citation: bo(5, "Doctors and specialists", "Allergy testing 100% 70% after deductible 1 testing (based on provider type)"),
    status: "confirmed",
  },
  {
    key: "hearing_exam",
    label: "Hearing examination",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "1 exam",
    preAuth: "not_stated",
    citation: bo(5, "Doctors and specialists", "Hearing examination 100% 70% after deductible 1 exam"),
    status: "confirmed",
  },
  {
    key: "routine_eye_exam",
    label: "Routine eye exam",
    group: "diagnostics",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "1 exam",
    preAuth: "not_stated",
    citation: bo(5, "Doctors and specialists", "Routine eye exam 100% 70% after deductible 1 exam"),
    status: "needs_clarification",
    note: "Conflict: the exclusions say 'Vision exams, glasses, and contacts aren't covered except after eye surgery' (p.15). Possibly reconciled by the vision add-on. Confirm with the SPD.",
  },
  // Preventive --------------------------------------------------------------
  {
    key: "preventive_routine",
    label: "Preventive care: routine care (birth through adulthood)",
    group: "preventive",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(6, "Preventive care", "Routine care (birth through adulthood) 100% 70% after deductible"),
    status: "confirmed",
  },
  {
    key: "preventive_immunizations",
    label: "Immunizations",
    group: "preventive",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    specialConditions: "Vaccines for work or travel aren't covered. Preventive vaccines are (p.13).",
    citation: bo(6, "Preventive care", "Immunizations 100% 70% after deductible"),
    status: "confirmed",
  },
  {
    key: "preventive_screenings",
    label: "Screenings",
    group: "preventive",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(6, "Preventive care", "Screenings 100% 70% after deductible"),
    status: "confirmed",
  },
  // Behavioral health -------------------------------------------------------
  {
    key: "mental_health",
    label: "Mental health (hospitalized, office or virtual visit)",
    group: "behavioral_health",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "unclear",
    preAuthListRefs: ["A"],
    preAuthNote:
      "The row reads 'While hospitalized, office or virtual visit' next to 'Pre-authorization required'. The A–T list requires it for inpatient mental-health admissions (A). Whether office or virtual visits need it is unclear.",
    citation: MH_ROW,
    status: "needs_clarification",
  },
  {
    key: "substance_use",
    label: "Substance use disorder treatment",
    group: "behavioral_health",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required_partial",
    preAuthListRefs: ["A", "I"],
    preAuthNote:
      "Required for inpatient substance use admissions (A) and outpatient substance use disorder programs (I). Office or virtual visits share the ambiguity of the mental-health row.",
    citation: MH_ROW,
    status: "needs_clarification",
  },
  // Therapy / rehab ---------------------------------------------------------
  {
    key: "physical_therapy",
    label: "Physical therapy",
    group: "therapy_rehab",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    specialConditions: "Includes virtual visits. Maintenance therapy after maximum improvement is excluded (p.13).",
    citation: THERAPY_ROW,
    status: "confirmed",
  },
  {
    key: "speech_therapy",
    label: "Speech therapy",
    group: "therapy_rehab",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    specialConditions: "Includes virtual visits. Therapy for developmental delays is excluded unless part of a diagnosed mental health condition or preventive care (p.12).",
    citation: THERAPY_ROW,
    status: "confirmed",
  },
  {
    key: "occupational_therapy",
    label: "Occupational therapy",
    group: "therapy_rehab",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    specialConditions: "Includes virtual visits.",
    citation: THERAPY_ROW,
    status: "confirmed",
  },
  {
    key: "home_health",
    label: "Home health care",
    group: "therapy_rehab",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["M"],
    citation: bo(6, "Specialty support", "Home health care 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "skilled_nursing",
    label: "Skilled nursing facility and rehabilitation",
    group: "therapy_rehab",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "120 days per 12-month period",
    preAuth: "required",
    preAuthListRefs: ["A"],
    citation: bo(6, "Specialty support", "Skilled nursing facility and rehabilitation 100% 70% after deductible 120 days per 12 month period Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "hospice",
    label: "Hospice care",
    group: "therapy_rehab",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "Lifetime maximum benefit of 180 days",
    preAuth: "required",
    preAuthListRefs: ["P"],
    citation: bo(6, "Specialty support", "Hospice care 100% 70% after deductible Lifetime maximum benefit of 180 days Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "cardiac_rehab",
    label: "Cardiac rehab",
    group: "therapy_rehab",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "Single 12-week period, max 36 sessions",
    preAuth: "not_stated",
    specialConditions: "Maintenance-level (Phase III) cardiac rehab is excluded (p.11).",
    citation: bo(6, "Specialty support", "Cardiac rehab visits 100% 70% after deductible Single 12-week period, max 36 sessions"),
    status: "confirmed",
  },
  {
    key: "pulmonary_therapy",
    label: "Pulmonary therapy (outpatient)",
    group: "therapy_rehab",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "Single 6-week period, up to 36 visits",
    preAuth: "not_stated",
    specialConditions: "Inpatient pulmonary therapy is covered under hospital charges.",
    citation: bo(
      7,
      "Specialty support",
      "Pulmonary therapy (outpatient) 100% 70% after deductible Inpatient pulmonary therapy covered under Covered for a single 6-week period, up to 36 visits hospital charges",
    ),
    status: "confirmed",
  },
  // Specialty ---------------------------------------------------------------
  {
    key: "dialysis",
    label: "Dialysis",
    group: "specialty",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["D"],
    citation: bo(6, "Specialty support", "Dialysis 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "oncology",
    label: "Oncology services (chemotherapy, radiation, cancer-related surgery)",
    group: "specialty",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["E"],
    citation: bo(4, "Hospital charges", "Oncology services 100% 70% after deductible (e.g., chemotherapy, radiation Pre-authorization required therapy, cancer-related surgery)"),
    status: "confirmed",
  },
  {
    key: "injections",
    label: "Injections",
    group: "specialty",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required_partial",
    preAuthListRefs: ["R"],
    preAuthNote: "Required for pain programs (injection therapy for pain programs).",
    citation: bo(4, "Hospital charges", "Injections 100% 70% after deductible Pre-authorization required for pain programs"),
    status: "confirmed",
  },
  {
    key: "infusion",
    label: "Infusion services",
    group: "specialty",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["L"],
    citation: bo(7, "Specialty support", "Infusion services 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "transplants",
    label: "Transplants",
    group: "specialty",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["B"],
    specialConditions: "Cornea transplants by any provider are covered as a separate benefit and paid the same as any other illness.",
    citation: bo(
      7,
      "Specialty support",
      "Transplants 100% 70% after deductible Cornea transplants performed by any provider are covered under the plan as a separate benefit and Pre-authorization required paid the same as any other illness",
    ),
    status: "confirmed",
  },
  {
    key: "hyperbaric_oxygen",
    label: "Hyperbaric oxygen treatments",
    group: "specialty",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["G"],
    specialConditions: "The exclusions list hyperbaric therapy as not covered unless for decompression or wound healing (p.11).",
    citation: bo(7, "Specialty support", "Hyperbaric oxygen treatments 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "tmj",
    label: "Temporomandibular joint (TMJ) dysfunction",
    group: "specialty",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "Up to $2,000",
    preAuth: "not_stated",
    citation: bo(7, "Specialty support", "Temporomandibular joint dysfunction 100% 70% after deductible Up to $2,000"),
    status: "confirmed",
  },
  // Equipment and supplies --------------------------------------------------
  {
    key: "dme",
    label: "Durable medical equipment",
    group: "equipment_supplies",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["H"],
    preAuthNote: "The pre-authorization list specifies 'over 30-day rental or purchase'. The benefits table says 'Pre-authorization required' without that qualifier.",
    citation: bo(7, "Supplies and equipment", "Durable medical equipment 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "hearing_aids",
    label: "Hearing aids and related supplies",
    group: "equipment_supplies",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "One hearing aid per ear every 48 months; up to $4,000",
    preAuth: "not_stated",
    citation: bo(7, "Supplies and equipment", "Hearing aids and related supplies 100% 70% after deductible One hearing aid per ear every 48 months Up to $4,000"),
    status: "confirmed",
  },
  {
    key: "prosthetics",
    label: "Prosthetics",
    group: "equipment_supplies",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required",
    preAuthListRefs: ["Q"],
    citation: bo(7, "Supplies and equipment", "Prosthetics 100% 70% after deductible Pre-authorization required"),
    status: "confirmed",
  },
  {
    key: "diabetic_supplies",
    label: "Diabetic education and supplies",
    group: "equipment_supplies",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "required_partial",
    preAuthListRefs: ["H"],
    preAuthNote: "Pre-authorization required for insulin pumps.",
    specialConditions: "Includes preventive and non-preventive education and supplies.",
    citation: bo(
      7,
      "Supplies and equipment",
      "Diabetic education and supplies 100% 70% after deductible Includes preventive and non-preventive Pre-authorization required for insulin pumps education and supplies",
    ),
    status: "confirmed",
  },
  // Reproductive and maternity ----------------------------------------------
  {
    key: "reproductive_underlying_cause",
    label: "Reproductive health: testing, diagnosis and treatment of underlying cause",
    group: "reproductive_maternity",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(8, "Reproductive health", "Testing, diagnosis and treatment 100% 70% after deductible of underlying cause"),
    status: "confirmed",
  },
  {
    key: "infertility_treatment",
    label: "Infertility treatment and procedures",
    group: "reproductive_maternity",
    inNetwork: NOT_COVERED,
    outOfNetwork: NOT_COVERED,
    preAuth: "not_stated",
    citation: bo(8, "Reproductive health", "Infertility treatment and procedures Not covered Not covered"),
    status: "confirmed",
  },
  {
    key: "contraceptive_management",
    label: "Contraceptive management",
    group: "reproductive_maternity",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    specialConditions: "Deductible waived for preventive (per law). OTC contraceptives not covered.",
    citation: bo(8, "Reproductive health", "Contraceptive management 100% 70% after deductible Deductible waived for preventive (per law). OTC contraceptives not covered"),
    status: "confirmed",
  },
  {
    key: "maternity_preventive_prenatal",
    label: "Maternity: preventive prenatal and breastfeeding support",
    group: "reproductive_maternity",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(8, "Maternity care", "Preventive prenatal 100% 70% after deductible and breastfeeding support"),
    status: "confirmed",
  },
  {
    key: "maternity_lactation",
    label: "Maternity: lactation consultations",
    group: "reproductive_maternity",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(8, "Maternity care", "Lactation consultations 100% 70% after deductible"),
    status: "confirmed",
  },
  {
    key: "maternity_other_care",
    label: "Maternity: all other prenatal and postnatal care",
    group: "reproductive_maternity",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(8, "Maternity care", "All other prenatal and postnatal care 100% 70% after deductible"),
    status: "confirmed",
  },
  {
    key: "maternity_delivery",
    label: "Maternity: delivery",
    group: "reproductive_maternity",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "unclear",
    preAuthNote:
      "The delivery row doesn't mention pre-authorization. List item A covers inpatient hospital admissions and C covers stays over 48 hours. The source doesn't say how these apply to delivery admissions.",
    specialConditions: "Home births at home or unlicensed locations aren't covered unless approved as lower cost (p.13).",
    citation: bo(8, "Maternity care", "Delivery 100% 70% after deductible"),
    status: "needs_clarification",
  },
  // Wellness ----------------------------------------------------------------
  {
    key: "acupuncture",
    label: "Acupuncture",
    group: "wellness",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "20 visits",
    preAuth: "not_stated",
    citation: bo(8, "Wellness therapies", "Acupuncture 100% 70% after deductible 20 visits"),
    status: "confirmed",
    note: "The public page says 'up to 20 sessions each of acupuncture and chiropractics'. The period (per year?) is not stated.",
  },
  {
    key: "chiropractic",
    label: "Chiropractic care / spinal manipulation",
    group: "wellness",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    limits: "20 visits",
    preAuth: "not_stated",
    citation: bo(8, "Wellness therapies", "Chiropractic care/spinal manipulation 100% 70% after deductible 20 visits"),
    status: "confirmed",
  },
  // Other -------------------------------------------------------------------
  {
    key: "all_other_eligible",
    label: "All other eligible medical expenses",
    group: "other",
    inNetwork: IN_100,
    outOfNetwork: OON_70,
    preAuth: "not_stated",
    citation: bo(9, "All other eligible medical expenses", "All other eligible medical expenses In network Out of network 100% 70% after deductible"),
    status: "confirmed",
  },
  // Pharmacy ----------------------------------------------------------------
  {
    key: "pharmacy_retail",
    label: "Prescriptions: retail pharmacy (30-day supply)",
    group: "pharmacy",
    inNetwork: null,
    outOfNetwork: null,
    copay: "Generic $10 · Preferred brand $30 · Non-preferred brand $50 · No deductible",
    preAuth: "not_stated",
    citation: bo(
      9,
      "Drug type",
      "Retail pharmacy: 30-day supply Generic drug $10 No deductible Brand name drug (preferred) $30 No deductible Brand name drug (non-preferred) $50 No deductible",
    ),
    status: "confirmed",
    note: "Network status for pharmacy is not stated in the source.",
  },
  {
    key: "pharmacy_mail_order",
    label: "Prescriptions: mail order (90-day supply)",
    group: "pharmacy",
    inNetwork: null,
    outOfNetwork: null,
    copay: "Generic $10 · Brand $30 · Non-preferred $50 · No deductible",
    preAuth: "not_stated",
    citation: bo(
      9,
      "Drug type",
      "Mail order pharmacy: 90-day supply Generic drug $10 No deductible Brand name drug $30 No deductible Non-preferred drug $50 No deductible",
    ),
    status: "confirmed",
  },
  {
    key: "pharmacy_specialty",
    label: "Prescriptions: specialty drugs (30-day supply)",
    group: "pharmacy",
    inNetwork: null,
    outOfNetwork: null,
    copay: "$50 · No deductible",
    preAuth: "not_stated",
    citation: bo(9, "Drug type", "Specialty drugs: 30-day supply $50 No deductible"),
    status: "confirmed",
  },
  {
    key: "pharmacy_preventive",
    label: "Prescriptions: preventive drugs",
    group: "pharmacy",
    inNetwork: null,
    outOfNetwork: null,
    copay: "No charge (as classified by HHS)",
    preAuth: "not_stated",
    citation: bo(9, "Drug type", "Preventive drug No charge As classified by HHS"),
    status: "confirmed",
  },
];
